"""Plan Contable General Empresarial (PCGE, versión modificada 2019 — vigente
desde el 01/01/2020), catálogo de fábrica del ERP.

**Por qué vive en código y no en configuración.** El resto del módulo evita
cablear cuentas (`regla_asiento`, `parametro_empresa`) porque el plan de
cuentas es decisión de cada empresa. El PCGE no es eso: es el catálogo
**oficial** que el Consejo Normativo de Contabilidad obliga a usar en el
Perú, igual para todas las empresas del grupo y para el contador externo.
Tenerlo acá es lo que evita inventar el número de una cuenta que ya existe
—el problema que este catálogo resuelve—. Lo que sigue siendo configurable
es **qué cuenta usa cada evento** (`regla_asiento`) y qué cuentas la empresa
activa o agrega.

**Cobertura.** Elementos 1 a 7 y 9 completos a nivel de rubro (dos dígitos),
con las divisionarias de tres a cinco dígitos que una operación de
restaurante realmente usa. De los elementos 8 y 0:

- del **8** se siembran solo `87` (participaciones de los trabajadores) y
  `88` (impuesto a la renta), que sí son gasto del ejercicio. Los saldos
  intermediarios de gestión (`80`-`85`) y la determinación del resultado
  (`89`) no se siembran: son cuentas de cierre anual que arma el contador
  externo, y los estados financieros de este módulo calculan el resultado
  directamente de los elementos 6, 7 y 9 sin pasar por `89`;
- el **0** (cuentas de orden) queda fuera: no mueve activo, pasivo ni
  resultado, y hoy ningún proceso del ERP lo alimenta.

Las dos omisiones están anotadas como deuda en `ROADMAP.md`.

**Elemento 9.** El PCGE lo deja de denominación libre. El ERP fija la
convención más difundida en el Perú y la documenta acá para que nadie la
adivine: 91 costo de producción, 94 gastos de administración, 95 gastos de
ventas, 97 gastos financieros.
"""

# Elemento → tipo de `cuenta_contable`. El 8 solo se siembra en 87/88, los
# dos que son gasto del ejercicio; por eso el elemento entero mapea a gasto.
TIPO_POR_ELEMENTO = {
    "1": "activo",
    "2": "activo",
    "3": "activo",
    "4": "pasivo",
    "5": "patrimonio",
    "6": "gasto",
    "7": "ingreso",
    "8": "gasto",
    "9": "gasto",
}

#: Catálogo oficial. Orden jerárquico: el padre siempre aparece antes que sus
#: divisionarias, que es lo que permite armar el árbol en una sola pasada.
CUENTAS: tuple[tuple[str, str], ...] = (
    # --- Elemento 1: Activo disponible y exigible ----------------------------
    ("10", "Efectivo y equivalentes de efectivo"),
    ("101", "Caja"),
    ("102", "Fondos fijos"),
    ("103", "Efectivo y equivalentes de efectivo en tránsito"),
    ("104", "Cuentas corrientes en instituciones financieras"),
    ("1041", "Cuentas corrientes operativas"),
    ("1042", "Cuentas corrientes para fines específicos"),
    ("105", "Otros equivalentes de efectivo"),
    ("106", "Depósitos en instituciones financieras"),
    ("1061", "Depósitos de ahorro"),
    ("1062", "Depósitos a plazo"),
    ("107", "Fondos sujetos a restricción"),
    ("11", "Inversiones financieras"),
    ("111", "Inversiones mantenidas para negociación"),
    ("112", "Otras inversiones financieras"),
    ("12", "Cuentas por cobrar comerciales - Terceros"),
    ("121", "Facturas, boletas y otros comprobantes por cobrar"),
    ("1211", "No emitidas"),
    ("1212", "Emitidas en cartera"),
    ("1213", "En cobranza"),
    ("1214", "En descuento"),
    ("122", "Anticipos de clientes"),
    ("123", "Letras por cobrar"),
    ("1231", "En cartera"),
    ("1232", "En cobranza"),
    ("1233", "En descuento"),
    ("129", "Cobranza dudosa"),
    ("13", "Cuentas por cobrar comerciales - Relacionadas"),
    ("131", "Facturas, boletas y otros comprobantes por cobrar"),
    ("132", "Anticipos recibidos"),
    ("133", "Letras por cobrar"),
    ("139", "Cobranza dudosa"),
    ("14", "Cuentas por cobrar al personal, accionistas (socios), directores y gerentes"),
    ("141", "Personal"),
    ("142", "Accionistas (socios)"),
    ("143", "Directores"),
    ("144", "Gerentes"),
    ("149", "Diversas"),
    ("16", "Cuentas por cobrar diversas - Terceros"),
    ("161", "Préstamos"),
    ("162", "Reclamaciones a terceros"),
    ("163", "Intereses, regalías y dividendos"),
    ("164", "Depósitos otorgados en garantía"),
    ("165", "Venta de activo inmovilizado"),
    ("169", "Cobranza dudosa"),
    ("17", "Cuentas por cobrar diversas - Relacionadas"),
    ("18", "Servicios y otros contratados por anticipado"),
    ("181", "Costos financieros"),
    ("182", "Seguros"),
    ("183", "Alquileres"),
    ("185", "Mantenimiento de activos inmovilizados"),
    ("189", "Otros gastos contratados por anticipado"),
    ("19", "Estimación de cuentas de cobranza dudosa"),
    ("191", "Cuentas por cobrar comerciales - Terceros"),
    ("192", "Cuentas por cobrar comerciales - Relacionadas"),
    ("193", "Cuentas por cobrar al personal, accionistas (socios), directores y gerentes"),
    ("194", "Cuentas por cobrar diversas - Terceros"),
    ("195", "Cuentas por cobrar diversas - Relacionadas"),
    # --- Elemento 2: Activo realizable ---------------------------------------
    ("20", "Mercaderías"),
    ("201", "Mercaderías manufacturadas"),
    ("202", "Mercaderías de extracción"),
    ("203", "Mercaderías agropecuarias y piscícolas"),
    ("204", "Mercaderías inmuebles"),
    ("208", "Otras mercaderías"),
    ("21", "Productos terminados"),
    ("211", "Productos manufacturados"),
    ("215", "Existencias de servicios terminados"),
    ("217", "Otros productos terminados"),
    ("22", "Subproductos, desechos y desperdicios"),
    ("221", "Subproductos"),
    ("222", "Desechos y desperdicios"),
    ("23", "Productos en proceso"),
    ("231", "Productos en proceso de manufactura"),
    ("24", "Materias primas"),
    ("241", "Materias primas para productos manufacturados"),
    ("25", "Materiales auxiliares, suministros y repuestos"),
    ("251", "Materiales auxiliares"),
    ("252", "Suministros"),
    ("253", "Repuestos"),
    ("26", "Envases y embalajes"),
    ("261", "Envases"),
    ("262", "Embalajes"),
    ("27", "Activos no corrientes mantenidos para la venta"),
    ("28", "Existencias por recibir"),
    ("281", "Mercaderías"),
    ("284", "Materias primas"),
    ("285", "Materiales auxiliares, suministros y repuestos"),
    ("286", "Envases y embalajes"),
    ("29", "Desvalorización de existencias"),
    ("291", "Mercaderías"),
    ("292", "Productos terminados"),
    ("294", "Materias primas"),
    ("295", "Materiales auxiliares, suministros y repuestos"),
    ("296", "Envases y embalajes"),
    # --- Elemento 3: Activo inmovilizado -------------------------------------
    ("30", "Inversiones mobiliarias"),
    ("31", "Inversiones inmobiliarias"),
    ("311", "Terrenos"),
    ("312", "Edificaciones"),
    ("32", "Activos por derecho de uso"),
    ("321", "Inversiones inmobiliarias"),
    ("322", "Propiedad, planta y equipo"),
    ("323", "Intangibles"),
    ("33", "Propiedad, planta y equipo"),
    ("331", "Terrenos"),
    ("332", "Edificaciones"),
    ("333", "Maquinarias y equipos de explotación"),
    ("334", "Unidades de transporte"),
    ("335", "Muebles y enseres"),
    ("336", "Equipos diversos"),
    ("337", "Herramientas y unidades de reemplazo"),
    ("338", "Unidades por recibir"),
    ("339", "Construcciones y obras en curso"),
    ("34", "Intangibles"),
    ("341", "Concesiones, licencias y otros derechos"),
    ("342", "Patentes y propiedad industrial"),
    ("343", "Programas de computadora (software)"),
    ("345", "Fórmulas, diseños y prototipos"),
    ("347", "Plusvalía mercantil"),
    ("349", "Otros activos intangibles"),
    ("35", "Activos biológicos"),
    ("36", "Desvalorización de activo inmovilizado"),
    ("37", "Activo diferido"),
    ("371", "Impuesto a la renta diferido"),
    ("372", "Participaciones de los trabajadores diferidas"),
    ("373", "Intereses diferidos"),
    ("38", "Otros activos"),
    ("39", "Depreciación y amortización acumulados"),
    ("391", "Depreciación acumulada"),
    ("3911", "Inversiones inmobiliarias"),
    ("3912", "Activos por derecho de uso"),
    ("3913", "Propiedad, planta y equipo"),
    ("392", "Amortización acumulada"),
    ("393", "Agotamiento acumulado"),
    # --- Elemento 4: Pasivo --------------------------------------------------
    ("40", "Tributos, contraprestaciones y aportes al sistema de pensiones y de salud"),
    ("401", "Gobierno central"),
    ("4011", "Impuesto general a las ventas"),
    ("40111", "IGV - Cuenta propia"),
    ("40112", "IGV - Servicios prestados por no domiciliados"),
    ("40113", "IGV - Régimen de percepciones"),
    ("40114", "IGV - Régimen de retenciones"),
    ("4012", "Impuesto selectivo al consumo"),
    ("4017", "Impuesto a la renta"),
    ("40171", "Renta de tercera categoría"),
    ("40172", "Renta de cuarta categoría"),
    ("40173", "Renta de quinta categoría"),
    ("40174", "Renta de no domiciliados"),
    ("40175", "Otras retenciones"),
    ("4018", "Otros impuestos y contraprestaciones"),
    ("403", "Instituciones públicas"),
    ("4031", "ESSALUD"),
    ("4032", "ONP"),
    ("4033", "Contribución al SENATI"),
    ("4034", "Contribución al SENCICO"),
    ("4039", "Otras instituciones"),
    ("405", "Gobiernos regionales"),
    ("406", "Gobiernos locales"),
    ("407", "Administradoras de fondos de pensiones"),
    ("408", "Empresas prestadoras de servicios de salud"),
    ("409", "Otros costos administrativos e intereses"),
    ("41", "Remuneraciones y participaciones por pagar"),
    ("411", "Remuneraciones por pagar"),
    ("4111", "Sueldos y salarios por pagar"),
    ("4112", "Comisiones por pagar"),
    ("4114", "Gratificaciones por pagar"),
    ("4115", "Vacaciones por pagar"),
    ("413", "Participaciones de los trabajadores por pagar"),
    ("415", "Beneficios sociales de los trabajadores por pagar"),
    ("4151", "Compensación por tiempo de servicios"),
    ("4152", "Adelanto de compensación por tiempo de servicios"),
    ("417", "Administradoras de fondos de pensiones"),
    ("419", "Otras remuneraciones y participaciones por pagar"),
    ("42", "Cuentas por pagar comerciales - Terceros"),
    ("421", "Facturas, boletas y otros comprobantes por pagar"),
    ("4211", "No emitidas"),
    ("4212", "Emitidas"),
    ("422", "Anticipos a proveedores"),
    ("423", "Letras por pagar"),
    ("424", "Honorarios por pagar"),
    ("43", "Cuentas por pagar comerciales - Relacionadas"),
    ("44", "Cuentas por pagar a los accionistas (socios), directores y gerentes"),
    ("441", "Accionistas (socios)"),
    ("4411", "Préstamos"),
    ("4412", "Dividendos"),
    ("442", "Directores"),
    ("443", "Gerentes"),
    ("45", "Obligaciones financieras"),
    ("451", "Préstamos de instituciones financieras y otras entidades"),
    ("452", "Contratos de arrendamiento financiero"),
    ("453", "Obligaciones emitidas"),
    ("455", "Costos de financiación por pagar"),
    ("46", "Cuentas por pagar diversas - Terceros"),
    ("461", "Reclamaciones de terceros"),
    ("464", "Pasivos por instrumentos financieros"),
    ("465", "Pasivos por compra de activo inmovilizado"),
    ("469", "Otras cuentas por pagar diversas"),
    ("47", "Cuentas por pagar diversas - Relacionadas"),
    ("48", "Provisiones"),
    ("481", "Provisión para litigios"),
    ("486", "Provisión para garantías"),
    ("489", "Otras provisiones"),
    ("49", "Pasivo diferido"),
    ("491", "Impuesto a la renta diferido"),
    ("492", "Participaciones de los trabajadores diferidas"),
    ("493", "Intereses diferidos"),
    ("496", "Ingresos diferidos"),
    ("497", "Costos diferidos"),
    # --- Elemento 5: Patrimonio ----------------------------------------------
    ("50", "Capital"),
    ("501", "Capital social"),
    ("5011", "Acciones"),
    ("5012", "Participaciones"),
    ("502", "Acciones en tesorería"),
    ("51", "Acciones de inversión"),
    ("52", "Capital adicional"),
    ("521", "Primas (descuento) de acciones"),
    ("522", "Capitalizaciones en trámite"),
    ("523", "Reducciones de capital pendientes de formalización"),
    ("56", "Resultados no realizados"),
    ("57", "Excedente de revaluación"),
    ("58", "Reservas"),
    ("582", "Legal"),
    ("584", "Estatutarias"),
    ("585", "Facultativas"),
    ("589", "Otras reservas"),
    ("59", "Resultados acumulados"),
    ("591", "Utilidades no distribuidas"),
    ("5911", "Utilidades acumuladas"),
    ("5912", "Ingresos de años anteriores"),
    ("592", "Pérdidas acumuladas"),
    ("5921", "Pérdidas acumuladas"),
    ("5922", "Gastos de años anteriores"),
    # --- Elemento 6: Gastos por naturaleza -----------------------------------
    ("60", "Compras"),
    ("601", "Mercaderías"),
    ("6011", "Mercaderías manufacturadas"),
    ("602", "Materias primas"),
    ("6021", "Materias primas para productos manufacturados"),
    ("603", "Materiales auxiliares, suministros y repuestos"),
    ("6031", "Materiales auxiliares"),
    ("6032", "Suministros"),
    ("6033", "Repuestos"),
    ("604", "Envases y embalajes"),
    ("6041", "Envases"),
    ("6042", "Embalajes"),
    ("609", "Costos vinculados con las compras"),
    ("6091", "Costos vinculados con las compras de mercaderías"),
    ("6092", "Costos vinculados con las compras de materias primas"),
    ("6093", "Costos vinculados con las compras de materiales auxiliares y repuestos"),
    ("6094", "Costos vinculados con las compras de envases y embalajes"),
    ("61", "Variación de existencias"),
    ("611", "Mercaderías"),
    ("612", "Materias primas"),
    ("613", "Materiales auxiliares, suministros y repuestos"),
    ("614", "Envases y embalajes"),
    ("62", "Gastos de personal, directores y gerentes"),
    ("621", "Remuneraciones"),
    ("6211", "Sueldos y salarios"),
    ("6212", "Comisiones"),
    ("6214", "Gratificaciones"),
    ("6215", "Vacaciones"),
    ("622", "Otras remuneraciones"),
    ("623", "Indemnizaciones al personal"),
    ("624", "Capacitación"),
    ("625", "Atención al personal"),
    ("627", "Seguridad, previsión social y otras contribuciones"),
    ("6271", "Régimen de prestaciones de salud"),
    ("6272", "Régimen de pensiones"),
    ("6273", "Seguro complementario de trabajo de riesgo"),
    ("6274", "Seguro de vida"),
    ("6276", "Contribuciones al SENATI"),
    ("628", "Retribuciones al directorio"),
    ("629", "Beneficios sociales de los trabajadores"),
    ("6291", "Compensación por tiempo de servicios"),
    ("6292", "Pensiones y jubilaciones"),
    ("63", "Gastos de servicios prestados por terceros"),
    ("631", "Transporte, correos y gastos de viaje"),
    ("6311", "Transporte"),
    ("6312", "Correos"),
    ("6313", "Alojamiento"),
    ("6314", "Alimentación"),
    ("6315", "Otros gastos de viaje"),
    ("632", "Asesoría y consultoría"),
    ("6321", "Administrativa"),
    ("6322", "Legal y tributaria"),
    ("6323", "Auditoría y contable"),
    ("6324", "Mercadotecnia"),
    ("6329", "Otros"),
    ("633", "Producción encargada a terceros"),
    ("634", "Mantenimiento y reparaciones"),
    ("6343", "Propiedad, planta y equipo"),
    ("6344", "Intangibles"),
    ("635", "Alquileres"),
    ("6351", "Terrenos"),
    ("6352", "Edificaciones"),
    ("6353", "Maquinarias y equipos de explotación"),
    ("6354", "Equipo de transporte"),
    ("6355", "Equipos diversos"),
    ("636", "Servicios básicos"),
    ("6361", "Energía eléctrica"),
    ("6362", "Gas"),
    ("6363", "Agua"),
    ("6364", "Teléfono"),
    ("6365", "Internet"),
    ("6367", "Cable"),
    ("6369", "Otros servicios"),
    ("637", "Publicidad, publicaciones, relaciones públicas"),
    ("6371", "Publicidad"),
    ("6372", "Publicaciones"),
    ("6373", "Relaciones públicas"),
    ("638", "Servicios de contratistas"),
    ("639", "Otros servicios prestados por terceros"),
    ("6391", "Gastos bancarios"),
    ("6392", "Gastos de laboratorio"),
    ("6399", "Otros"),
    ("64", "Gastos por tributos"),
    ("641", "Gobierno central"),
    ("6411", "Impuesto general a las ventas y selectivo al consumo"),
    ("6412", "Impuesto a las transacciones financieras"),
    ("6413", "Impuesto temporal a los activos netos"),
    ("6419", "Otros"),
    ("642", "Gobierno regional"),
    ("643", "Gobierno local"),
    ("6431", "Impuesto predial"),
    ("6432", "Arbitrios municipales y seguridad ciudadana"),
    ("6433", "Impuesto al patrimonio vehicular"),
    ("6434", "Licencia de funcionamiento"),
    ("6439", "Otros"),
    ("649", "Otros gastos por tributos"),
    ("65", "Otros gastos de gestión"),
    ("651", "Seguros"),
    ("652", "Regalías"),
    ("653", "Suscripciones y cotizaciones"),
    ("654", "Licencias y derechos de vigencia"),
    ("655", "Costo neto de enajenación de activos inmovilizados"),
    ("656", "Suministros"),
    ("658", "Gestión medioambiental"),
    ("659", "Otros gastos de gestión"),
    ("6591", "Donaciones"),
    ("6592", "Sanciones administrativas"),
    ("6599", "Otros gastos"),
    ("66", "Pérdida por medición de activos no financieros al valor razonable"),
    ("67", "Gastos financieros"),
    ("671", "Gastos en operaciones de endeudamiento y otros"),
    ("673", "Intereses por préstamos y otras obligaciones"),
    ("6731", "Préstamos de instituciones financieras y otras entidades"),
    ("6732", "Contratos de arrendamiento financiero"),
    ("674", "Gastos en operaciones de factoraje"),
    ("675", "Descuentos concedidos por pronto pago"),
    ("679", "Otros gastos financieros"),
    ("68", "Valuación y deterioro de activos y provisiones"),
    ("681", "Depreciación"),
    ("6811", "Depreciación de inversiones inmobiliarias"),
    ("6812", "Depreciación de activos por derecho de uso"),
    ("6813", "Depreciación de propiedad, planta y equipo - Costo"),
    ("682", "Amortización de intangibles"),
    ("684", "Valuación de activos"),
    ("6841", "Estimación de cuentas de cobranza dudosa"),
    ("6842", "Desvalorización de existencias"),
    ("685", "Deterioro del valor de los activos"),
    ("686", "Provisiones"),
    ("69", "Costo de ventas"),
    ("691", "Mercaderías"),
    ("6911", "Mercaderías manufacturadas"),
    ("692", "Productos terminados"),
    ("694", "Servicios"),
    ("695", "Gastos por desvalorización de existencias"),
    # --- Elemento 7: Ingresos ------------------------------------------------
    ("70", "Ventas"),
    ("701", "Mercaderías"),
    ("7011", "Mercaderías manufacturadas"),
    ("702", "Productos terminados"),
    ("7021", "Productos manufacturados"),
    ("703", "Subproductos, desechos y desperdicios"),
    ("704", "Prestación de servicios"),
    ("7041", "Terceros"),
    ("7042", "Relacionadas"),
    ("709", "Devoluciones sobre ventas"),
    ("7091", "Mercaderías"),
    ("7092", "Productos terminados"),
    ("7094", "Prestación de servicios"),
    ("71", "Variación de la producción almacenada"),
    ("711", "Variación de productos terminados"),
    ("713", "Variación de productos en proceso"),
    ("715", "Variación de existencias de servicios"),
    ("72", "Producción de activo inmovilizado"),
    ("73", "Descuentos, rebajas y bonificaciones obtenidos"),
    ("731", "Descuentos, rebajas y bonificaciones obtenidos"),
    ("74", "Descuentos, rebajas y bonificaciones concedidos"),
    ("741", "Descuentos, rebajas y bonificaciones concedidos"),
    ("75", "Otros ingresos de gestión"),
    ("751", "Servicios en beneficio del personal"),
    ("752", "Comisiones y corretajes"),
    ("753", "Regalías"),
    ("754", "Alquileres"),
    ("7541", "Terrenos"),
    ("7542", "Edificaciones"),
    ("7543", "Maquinarias y equipos de explotación"),
    ("7544", "Equipo de transporte"),
    ("7545", "Equipos diversos"),
    ("755", "Recuperación de cuentas de valuación"),
    ("7551", "Recuperación - Cuentas de cobranza dudosa"),
    ("7552", "Recuperación - Desvalorización de existencias"),
    ("756", "Enajenación de activos inmovilizados"),
    ("759", "Otros ingresos de gestión"),
    ("7591", "Subsidios gubernamentales"),
    ("7592", "Donaciones"),
    ("7599", "Otros ingresos de gestión"),
    ("76", "Ganancia por medición de activos no financieros al valor razonable"),
    ("77", "Ingresos financieros"),
    ("772", "Rendimientos ganados"),
    ("7721", "Depósitos en instituciones financieras"),
    ("773", "Dividendos"),
    ("775", "Descuentos obtenidos por pronto pago"),
    ("779", "Otros ingresos financieros"),
    ("79", "Cargas imputables a cuentas de costos y gastos"),
    ("791", "Cargas imputables a cuentas de costos y gastos"),
    ("792", "Gastos financieros imputables a existencias o activos inmovilizados"),
    # --- Elemento 8: solo lo que es gasto del ejercicio -----------------------
    ("87", "Participaciones de los trabajadores"),
    ("871", "Participación de los trabajadores - Corriente"),
    ("872", "Participación de los trabajadores - Diferida"),
    ("88", "Impuesto a la renta"),
    ("881", "Impuesto a la renta - Corriente"),
    ("882", "Impuesto a la renta - Diferido"),
    # --- Elemento 9: gastos por función (denominación libre, ver módulo) ------
    ("91", "Costo de producción"),
    ("94", "Gastos de administración"),
    ("95", "Gastos de ventas"),
    ("97", "Gastos financieros"),
)

#: Índice por código, para resolver una cuenta sin recorrer la tupla.
DENOMINACIONES: dict[str, str] = dict(CUENTAS)


def tipo_de(codigo: str) -> str:
    """Tipo de `cuenta_contable` que le toca a un código del PCGE.

    Se deriva del elemento (primer dígito) y no se declara cuenta por cuenta:
    el PCGE ya ordenó el catálogo por naturaleza, y repetirlo sería una lista
    de 400 líneas que se desincroniza.
    """
    try:
        return TIPO_POR_ELEMENTO[codigo[0]]
    except (IndexError, KeyError) as e:
        raise ValueError(f"código fuera del PCGE: {codigo!r}") from e


def padre_de(codigo: str) -> str | None:
    """Código del padre inmediato dentro del catálogo, o `None` si es rubro.

    El padre es el prefijo más largo que exista en el catálogo, no
    simplemente `codigo[:-1]`: hay divisionarias que saltan un nivel
    (`40111` cuelga de `4011`, `6011` de `601`) y rubros que no cuelgan de
    nada porque su elemento no se siembra completo.
    """
    for largo in range(len(codigo) - 1, 1, -1):
        prefijo = codigo[:largo]
        if prefijo in DENOMINACIONES:
            return prefijo
    return None
