"""slice venta: usuario minimo, trabajador, productos base, venta

Revision ID: 08c7aa59dd6e
Revises: a06c1d0a0913
Create Date: 2026-07-20 15:52:38.538073

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op  # noqa: F401

revision: str = '08c7aa59dd6e'
down_revision: str | None = 'a06c1d0a0913'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('grupo_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('natural', 'juridico', name='tipo_cliente', native_enum=False), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('ruc', sa.String(length=11), nullable=True),
    sa.Column('contacto', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], name=op.f('fk_cliente_grupo_id_grupo')),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], name=op.f('fk_cliente_persona_id_persona')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cliente'))
    )
    op.create_table('usuario',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=True),
    sa.Column('nombre_display', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.Enum('humano', 'agente_ia', name='tipo_usuario', native_enum=False), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], name=op.f('fk_usuario_persona_id_persona')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('username', name=op.f('uq_usuario_username'))
    )
    op.create_table('receta',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rendimiento_cantidad', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('rendimiento_unidad_medida_id', sa.Uuid(), nullable=False),
    sa.Column('flexible', sa.Boolean(), nullable=False),
    sa.Column('criterio_ajuste', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rendimiento_unidad_medida_id'], ['unidad_medida.id'], name=op.f('fk_receta_rendimiento_unidad_medida_id_unidad_medida')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receta'))
    )
    op.create_table('trabajador',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('tipo_vinculo', sa.Enum('planilla', 'practicante', 'locacion_servicios', name='tipo_vinculo_trabajador', native_enum=False), nullable=False),
    sa.Column('regimen_laboral', sa.String(length=50), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_cese', sa.Date(), nullable=True),
    sa.Column('remuneracion_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sistema_pensiones', sa.Enum('onp', 'afp', name='sistema_pensiones', native_enum=False), nullable=True),
    sa.Column('afp_nombre', sa.String(length=50), nullable=True),
    sa.Column('tiene_poderes', sa.Boolean(), nullable=False),
    sa.Column('registra_asistencia', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'cesado', 'suspendido', name='estado_trabajador', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_trabajador_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], name=op.f('fk_trabajador_persona_id_persona')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_trabajador_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trabajador'))
    )
    op.create_table('articulo',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id_interno', sa.String(length=4), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=True),
    sa.Column('unidad_medida_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('costo_promedio', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('archivado', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('fk_articulo_categoria_id_categoria')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_articulo_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidad_medida.id'], name=op.f('fk_articulo_unidad_medida_id_unidad_medida')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articulo')),
    sa.UniqueConstraint('id_interno', name=op.f('uq_articulo_id_interno'))
    )
    op.create_table('punto_venta',
    sa.Column('sucursal_id', sa.Uuid(), nullable=False),
    sa.Column('canal', sa.Enum('trabajador', 'web', 'kiosko', name='canal_punto_venta', native_enum=False), nullable=False),
    sa.Column('hardware_id', sa.String(length=50), nullable=True),
    sa.Column('modalidades_habilitadas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('datos_minimos_por_modalidad', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('politica_pago', sa.Enum('adelantado', 'al_finalizar', name='politica_pago_punto_venta', native_enum=False), nullable=False),
    sa.Column('kpis', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_punto_venta_sucursal_id_sucursal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_punto_venta'))
    )
    op.create_table('producto_comercial',
    sa.Column('id_interno', sa.String(length=4), nullable=False),
    sa.Column('marca_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('receta_id', sa.Uuid(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('margen_contribucion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('empaque_id', sa.Uuid(), nullable=True),
    sa.Column('modalidades_empaque', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empaque_id'], ['articulo.id'], name=op.f('fk_producto_comercial_empaque_id_articulo')),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], name=op.f('fk_producto_comercial_marca_id_marca')),
    sa.ForeignKeyConstraint(['receta_id'], ['receta.id'], name=op.f('fk_producto_comercial_receta_id_receta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producto_comercial')),
    sa.UniqueConstraint('id_interno', name=op.f('uq_producto_comercial_id_interno'))
    )
    op.create_table('receta_item',
    sa.Column('receta_id', sa.Uuid(), nullable=False),
    sa.Column('articulo_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('merma_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], name=op.f('fk_receta_item_articulo_id_articulo')),
    sa.ForeignKeyConstraint(['receta_id'], ['receta.id'], name=op.f('fk_receta_item_receta_id_receta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receta_item'))
    )
    op.create_table('sku',
    sa.Column('articulo_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], name=op.f('fk_sku_articulo_id_articulo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sku')),
    sa.UniqueConstraint('codigo', name=op.f('uq_sku_codigo'))
    )
    op.create_table('venta',
    sa.Column('sucursal_id', sa.Uuid(), nullable=False),
    sa.Column('punto_venta_id', sa.Uuid(), nullable=False),
    sa.Column('canal', sa.Enum('pdv', 'agente_ia', 'delivery', name='canal_venta', native_enum=False), nullable=False),
    sa.Column('modalidad', sa.Enum('mesa', 'takeout', 'delivery', name='modalidad_venta', native_enum=False), nullable=False),
    sa.Column('cotizacion_id', sa.Uuid(), nullable=True),
    sa.Column('cliente_id', sa.Uuid(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('orden', 'pagada', 'facturada', 'anulada', name='estado_venta', native_enum=False), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('repartidor_externo_plataforma', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_venta_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['punto_venta.id'], name=op.f('fk_venta_punto_venta_id_punto_venta')),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_venta_sucursal_id_sucursal')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_venta_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venta')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_venta_idempotency_key'))
    )
    op.create_table('venta_item',
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('producto_comercial_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_comercial_id'], ['producto_comercial.id'], name=op.f('fk_venta_item_producto_comercial_id_producto_comercial')),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name=op.f('fk_venta_item_venta_id_venta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venta_item'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta_item')
    op.drop_table('venta')
    op.drop_table('sku')
    op.drop_table('receta_item')
    op.drop_table('producto_comercial')
    op.drop_table('punto_venta')
    op.drop_table('articulo')
    op.drop_table('trabajador')
    op.drop_table('receta')
    op.drop_table('usuario')
    op.drop_table('cliente')
    # ### end Alembic commands ###
