"""decision_gerencial: acta de decision gerencial (RN-GER-002)

Documentada en data-model.md §8c desde el slice de Gerencia (2026-07-22),
sin modelo ni migracion hasta hoy. Materializa el acta: una decision verbal
no tiene validez operativa.

`referencia_tipo` + `referencia_id` son polimorficos SIN FK a proposito: la
decision aplica a una OC escalada, una campana sobre presupuesto o una
sancion, y ninguna de esas tablas puede ganar una FK hacia `shared` ni
`shared` hacia ellas -- seria el acoplamiento entre modulos que la
arquitectura evita. El indice compuesto sirve el acceso real ("que decidio
Gerencia sobre esto") desde el modulo que tiene el recurso en pantalla.

No reemplaza el rastro de `parametro_empresa` (propuesta/aprobacion con
motivo, RN-GER-009): por eso mismo se descarto
`parametro_empresa.decision_gerencial_id`. Esta tabla es para las
decisiones que no tienen su propio flujo tipado.

Revision ID: 1805c0904c5c
Revises: e4a2f9c17b3d
Create Date: 2026-08-03 14:56:53.600721

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = '1805c0904c5c'
down_revision: str | None = 'e4a2f9c17b3d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_gerencial',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('aprobacion', 'directiva', 'accion_correctiva', 'decision_estrategica', name='tipo_decision_gerencial', native_enum=False), nullable=False),
    sa.Column('referencia_tipo', sa.String(length=50), nullable=False),
    sa.Column('referencia_id', sa.Uuid(), nullable=False),
    sa.Column('decidido_por_id', sa.Uuid(), nullable=False),
    sa.Column('sustento', sa.Text(), nullable=False),
    sa.Column('resultado', sa.Enum('aprobado', 'aprobado_con_condiciones', 'rechazado', 'diferido', 'elevado_a_socios', name='resultado_decision_gerencial', native_enum=False), nullable=False),
    sa.Column('condiciones', sa.Text(), nullable=True),
    sa.Column('ejecuta_area', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('archivo_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['archivo_id'], ['archivo.id'], name=op.f('fk_decision_gerencial_archivo_id_archivo')),
    sa.ForeignKeyConstraint(['decidido_por_id'], ['usuario.id'], name=op.f('fk_decision_gerencial_decidido_por_id_usuario')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_decision_gerencial_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_gerencial'))
    )
    op.create_index('ix_decision_gerencial_referencia', 'decision_gerencial', ['referencia_tipo', 'referencia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_decision_gerencial_referencia', table_name='decision_gerencial')
    op.drop_table('decision_gerencial')
    # ### end Alembic commands ###
