"""slice_assets_activo_mantenimiento_vigencia

Revision ID: 30270ac890b1
Revises: c4f3e14f5bce
Create Date: 2026-09-09 02:09:35.613163

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = "30270ac890b1"
down_revision: str | None = "69f4ca1d58f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documento_vigencia",
        sa.Column("empresa_id", sa.Uuid(), nullable=False),
        sa.Column(
            "sujeto_tipo",
            sa.Enum(
                "activo",
                "sucursal",
                "empresa",
                "trabajador",
                name="sujeto_documento_vigencia",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("sujeto_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tipo_documento",
            sa.Enum(
                "soat",
                "revision_tecnica",
                "tarjeta_propiedad",
                "poliza_seguro",
                "garantia",
                "licencia_funcionamiento",
                "certificado_defensa_civil",
                "fumigacion",
                "registro_sanitario",
                "carne_sanidad",
                "licencia_conducir",
                "otro",
                name="tipo_documento_vigencia",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("numero", sa.String(length=60), nullable=True),
        sa.Column("emisor", sa.String(length=120), nullable=True),
        sa.Column("fecha_emision", sa.Date(), nullable=True),
        sa.Column("fecha_vencimiento", sa.Date(), nullable=False),
        sa.Column("dias_aviso", sa.Integer(), nullable=False),
        sa.Column("renovado_por_id", sa.Uuid(), nullable=True),
        sa.Column("aviso_proximo_en", sa.Date(), nullable=True),
        sa.Column("aviso_vencido_en", sa.Date(), nullable=True),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sujeto_tipo IN ('activo', 'sucursal', 'empresa', 'trabajador')",
            name=op.f("ck_documento_vigencia_sujeto_documento_vigencia"),
        ),
        sa.CheckConstraint(
            "tipo_documento IN ('soat', 'revision_tecnica', 'tarjeta_propiedad', 'poliza_seguro', 'garantia', 'licencia_funcionamiento', 'certificado_defensa_civil', 'fumigacion', 'registro_sanitario', 'carne_sanidad', 'licencia_conducir', 'otro')",
            name=op.f("ck_documento_vigencia_tipo_documento_vigencia"),
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"], ["empresa.id"], name=op.f("fk_documento_vigencia_empresa_id_empresa")
        ),
        sa.ForeignKeyConstraint(
            ["renovado_por_id"],
            ["documento_vigencia.id"],
            name=op.f("fk_documento_vigencia_renovado_por_id_documento_vigencia"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documento_vigencia")),
    )
    op.create_table(
        "activo",
        sa.Column("empresa_id", sa.Uuid(), nullable=False),
        sa.Column("sucursal_id", sa.Uuid(), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum("equipamiento", "vehiculo", name="tipo_activo", native_enum=False),
            nullable=False,
        ),
        sa.Column("id_interno", sa.String(length=8), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("categoria", sa.String(length=60), nullable=True),
        sa.Column("marca", sa.String(length=60), nullable=True),
        sa.Column("modelo", sa.String(length=60), nullable=True),
        sa.Column("numero_serie", sa.String(length=80), nullable=True),
        sa.Column("etiqueta_codigo", sa.String(length=40), nullable=True),
        sa.Column("fecha_compra", sa.Date(), nullable=True),
        sa.Column("valor_compra", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("vida_util_meses", sa.Integer(), nullable=True),
        sa.Column("proveedor_id", sa.Uuid(), nullable=True),
        sa.Column("comprobante_compra_id", sa.Uuid(), nullable=True),
        sa.Column("responsable_trabajador_id", sa.Uuid(), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "operativo", "en_mantenimiento", "de_baja", name="estado_activo", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("archivado", sa.Boolean(), nullable=False),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "estado IN ('operativo', 'en_mantenimiento', 'de_baja')",
            name=op.f("ck_activo_estado_activo"),
        ),
        sa.CheckConstraint(
            "tipo IN ('equipamiento', 'vehiculo')", name=op.f("ck_activo_tipo_activo")
        ),
        sa.ForeignKeyConstraint(
            ["comprobante_compra_id"],
            ["comprobante.id"],
            name=op.f("fk_activo_comprobante_compra_id_comprobante"),
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"], ["empresa.id"], name=op.f("fk_activo_empresa_id_empresa")
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"], ["sucursal.id"], name=op.f("fk_activo_sucursal_id_sucursal")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activo")),
        sa.UniqueConstraint("empresa_id", "id_interno", name="uq_activo_id_interno"),
    )
    op.create_table(
        "plan_mantenimiento",
        sa.Column("activo_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("cada_dias", sa.Integer(), nullable=True),
        sa.Column("cada_km", sa.Integer(), nullable=True),
        sa.Column("dias_aviso", sa.Integer(), nullable=False),
        sa.Column("km_aviso", sa.Integer(), nullable=False),
        sa.Column("proveedor_servicio_id", sa.Uuid(), nullable=True),
        sa.Column("km_base", sa.Integer(), nullable=True),
        sa.Column("ultima_fecha", sa.Date(), nullable=True),
        sa.Column("ultimo_km", sa.Integer(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("aviso_proximo_en", sa.Date(), nullable=True),
        sa.Column("aviso_vencido_en", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cada_dias IS NOT NULL OR cada_km IS NOT NULL",
            name=op.f("ck_plan_mantenimiento_plan_mantenimiento_frecuencia"),
        ),
        sa.ForeignKeyConstraint(
            ["activo_id"], ["activo.id"], name=op.f("fk_plan_mantenimiento_activo_id_activo")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_mantenimiento")),
    )
    op.create_table(
        "vehiculo",
        sa.Column("activo_id", sa.Uuid(), nullable=False),
        sa.Column("placa", sa.String(length=10), nullable=False),
        sa.Column(
            "tipo_vehiculo",
            sa.Enum(
                "moto",
                "auto",
                "camioneta",
                "camion",
                "otro",
                name="tipo_vehiculo",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("numero_motor", sa.String(length=40), nullable=True),
        sa.Column("numero_chasis", sa.String(length=40), nullable=True),
        sa.Column(
            "tenencia",
            sa.Enum("propio", "alquilado", name="tenencia_vehiculo", native_enum=False),
            nullable=False,
        ),
        sa.Column("kilometraje_actual", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tenencia IN ('propio', 'alquilado')", name=op.f("ck_vehiculo_tenencia_vehiculo")
        ),
        sa.CheckConstraint(
            "tipo_vehiculo IN ('moto', 'auto', 'camioneta', 'camion', 'otro')",
            name=op.f("ck_vehiculo_tipo_vehiculo"),
        ),
        sa.ForeignKeyConstraint(
            ["activo_id"], ["activo.id"], name=op.f("fk_vehiculo_activo_id_activo")
        ),
        sa.PrimaryKeyConstraint("activo_id", name=op.f("pk_vehiculo")),
        sa.UniqueConstraint("placa", name=op.f("uq_vehiculo_placa")),
    )
    op.create_table(
        "carga_combustible",
        sa.Column("vehiculo_id", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("galones", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("monto", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tipo_combustible", sa.String(length=20), nullable=True),
        sa.Column("km_odometro", sa.Integer(), nullable=False),
        sa.Column("comprobante_id", sa.Uuid(), nullable=False),
        sa.Column("km_recorridos", sa.Integer(), nullable=True),
        sa.Column("rendimiento_km_gal", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("anomalo", sa.Boolean(), nullable=False),
        sa.Column("registrado_por", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["comprobante_id"],
            ["comprobante.id"],
            name=op.f("fk_carga_combustible_comprobante_id_comprobante"),
        ),
        sa.ForeignKeyConstraint(
            ["registrado_por"],
            ["usuario.id"],
            name=op.f("fk_carga_combustible_registrado_por_usuario"),
        ),
        sa.ForeignKeyConstraint(
            ["vehiculo_id"],
            ["vehiculo.activo_id"],
            name=op.f("fk_carga_combustible_vehiculo_id_vehiculo"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carga_combustible")),
        sa.UniqueConstraint("comprobante_id", name=op.f("uq_carga_combustible_comprobante_id")),
    )
    op.create_table(
        "lectura_odometro",
        sa.Column("vehiculo_id", sa.Uuid(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("km", sa.Integer(), nullable=False),
        sa.Column(
            "origen",
            sa.Enum(
                "manual",
                "carga_combustible",
                "mantenimiento",
                name="origen_lectura_odometro",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("registrado_por", sa.Uuid(), nullable=False),
        sa.Column("nota", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "origen IN ('manual', 'carga_combustible', 'mantenimiento')",
            name=op.f("ck_lectura_odometro_origen_lectura_odometro"),
        ),
        sa.ForeignKeyConstraint(
            ["registrado_por"],
            ["usuario.id"],
            name=op.f("fk_lectura_odometro_registrado_por_usuario"),
        ),
        sa.ForeignKeyConstraint(
            ["vehiculo_id"],
            ["vehiculo.activo_id"],
            name=op.f("fk_lectura_odometro_vehiculo_id_vehiculo"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lectura_odometro")),
    )
    op.create_table(
        "orden_mantenimiento",
        sa.Column("activo_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum("programado", "adelantado", name="tipo_orden_mantenimiento", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "motivo_adelanto",
            sa.Enum(
                "desperfecto", "baja_productividad", name="motivo_adelanto_orden", native_enum=False
            ),
            nullable=True,
        ),
        sa.Column("fecha_programada", sa.Date(), nullable=True),
        sa.Column("fecha_realizada", sa.Date(), nullable=True),
        sa.Column("km_al_realizar", sa.Integer(), nullable=True),
        sa.Column("proveedor_servicio_id", sa.Uuid(), nullable=True),
        sa.Column("reportado_por", sa.Uuid(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("resultado", sa.Text(), nullable=True),
        sa.Column("costo", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("comprobante_id", sa.Uuid(), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "programada",
                "en_curso",
                "realizada",
                "cancelada",
                name="estado_orden_mantenimiento",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estado IN ('programada', 'en_curso', 'realizada', 'cancelada')",
            name=op.f("ck_orden_mantenimiento_estado_orden_mantenimiento"),
        ),
        sa.CheckConstraint(
            "motivo_adelanto IS NULL OR motivo_adelanto IN ('desperfecto', 'baja_productividad')",
            name=op.f("ck_orden_mantenimiento_motivo_adelanto_orden"),
        ),
        sa.CheckConstraint(
            "tipo IN ('programado', 'adelantado')",
            name=op.f("ck_orden_mantenimiento_tipo_orden_mantenimiento"),
        ),
        sa.ForeignKeyConstraint(
            ["activo_id"], ["activo.id"], name=op.f("fk_orden_mantenimiento_activo_id_activo")
        ),
        sa.ForeignKeyConstraint(
            ["comprobante_id"],
            ["comprobante.id"],
            name=op.f("fk_orden_mantenimiento_comprobante_id_comprobante"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan_mantenimiento.id"],
            name=op.f("fk_orden_mantenimiento_plan_id_plan_mantenimiento"),
        ),
        sa.ForeignKeyConstraint(
            ["reportado_por"],
            ["usuario.id"],
            name=op.f("fk_orden_mantenimiento_reportado_por_usuario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orden_mantenimiento")),
        sa.UniqueConstraint("comprobante_id", name=op.f("uq_orden_mantenimiento_comprobante_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orden_mantenimiento")
    op.drop_table("lectura_odometro")
    op.drop_table("carga_combustible")
    op.drop_table("vehiculo")
    op.drop_table("plan_mantenimiento")
    op.drop_table("activo")
    op.drop_table("documento_vigencia")
    # ### end Alembic commands ###
