"""slice purchases core: proveedor, orden_compra, recepcion

Revision ID: 4ff85f833b29
Revises: 617845c27651
Create Date: 2026-07-25 12:58:38.137515

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = '4ff85f833b29'
down_revision: str | None = '617845c27651'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('natural', 'juridico', name='tipo_proveedor', native_enum=False), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('ruc', sa.String(length=11), nullable=True),
    sa.Column('contacto', sa.String(length=255), nullable=True),
    sa.Column('formal', sa.Boolean(), nullable=False),
    sa.Column('clasificacion', sa.Enum('regular', 'preferente', name='clasificacion_proveedor', native_enum=False), nullable=False),
    sa.Column('condicion_pago', sa.Enum('contado', 'credito', name='condicion_pago_proveedor', native_enum=False), nullable=False),
    sa.Column('plazo_dias_credito', sa.Integer(), nullable=True),
    sa.Column('afecto_igv', sa.Boolean(), nullable=False),
    sa.Column('sujeto_spot', sa.Boolean(), nullable=False),
    sa.Column('porcentaje_deteccion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_proveedor_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], name=op.f('fk_proveedor_persona_id_persona')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proveedor'))
    )
    op.create_table('orden_compra',
    sa.Column('proveedor_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('insumo', 'activo', name='tipo_orden_compra', native_enum=False), nullable=False),
    sa.Column('cotizacion_id', sa.Uuid(), nullable=True),
    sa.Column('requerimiento_activo_id', sa.Uuid(), nullable=True),
    sa.Column('almacen_destino_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('borrador', 'emitida', 'recibida_parcial', 'recibida', 'anulada', name='estado_orden_compra', native_enum=False), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('creado_por', sa.Uuid(), nullable=False),
    sa.Column('emitido_por', sa.Uuid(), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['almacen_destino_id'], ['almacen.id'], name=op.f('fk_orden_compra_almacen_destino_id_almacen')),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name=op.f('fk_orden_compra_creado_por_usuario')),
    sa.ForeignKeyConstraint(['emitido_por'], ['usuario.id'], name=op.f('fk_orden_compra_emitido_por_usuario')),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], name=op.f('fk_orden_compra_proveedor_id_proveedor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orden_compra')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_orden_compra_idempotency_key'))
    )
    op.create_table('orden_compra_item',
    sa.Column('orden_compra_id', sa.Uuid(), nullable=False),
    sa.Column('articulo_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cantidad_recibida', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], name=op.f('fk_orden_compra_item_articulo_id_articulo')),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['orden_compra.id'], name=op.f('fk_orden_compra_item_orden_compra_id_orden_compra')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orden_compra_item'))
    )
    op.create_table('recepcion_compra',
    sa.Column('orden_compra_id', sa.Uuid(), nullable=False),
    sa.Column('comprobante_id', sa.Uuid(), nullable=True),
    sa.Column('recibido_por', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobante.id'], name=op.f('fk_recepcion_compra_comprobante_id_comprobante')),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['orden_compra.id'], name=op.f('fk_recepcion_compra_orden_compra_id_orden_compra')),
    sa.ForeignKeyConstraint(['recibido_por'], ['usuario.id'], name=op.f('fk_recepcion_compra_recibido_por_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recepcion_compra')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_recepcion_compra_idempotency_key'))
    )
    op.create_table('recepcion_item',
    sa.Column('recepcion_compra_id', sa.Uuid(), nullable=False),
    sa.Column('orden_compra_item_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad_recibida', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['orden_compra_item_id'], ['orden_compra_item.id'], name=op.f('fk_recepcion_item_orden_compra_item_id_orden_compra_item')),
    sa.ForeignKeyConstraint(['recepcion_compra_id'], ['recepcion_compra.id'], name=op.f('fk_recepcion_item_recepcion_compra_id_recepcion_compra')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recepcion_item'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recepcion_item')
    op.drop_table('recepcion_compra')
    op.drop_table('orden_compra_item')
    op.drop_table('orden_compra')
    op.drop_table('proveedor')
    # ### end Alembic commands ###
