"""slice accounting core: plan de cuentas, asiento, periodo y regla de mapeo

Revision ID: 5402d99333fa
Revises: af8a246e2c25
Create Date: 2026-07-25 15:16:26.263215

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = '5402d99333fa'
down_revision: str | None = 'af8a246e2c25'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuenta_contable',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('activo', 'pasivo', 'patrimonio', 'ingreso', 'gasto', name='tipo_cuenta_contable', native_enum=False), nullable=False),
    sa.Column('cuenta_padre_id', sa.Uuid(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_padre_id'], ['cuenta_contable.id'], name=op.f('fk_cuenta_contable_cuenta_padre_id_cuenta_contable')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_cuenta_contable_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cuenta_contable')),
    sa.UniqueConstraint('empresa_id', 'codigo', name=op.f('uq_cuenta_contable_empresa_id'))
    )
    op.create_table('periodo_contable',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('abierto', 'cerrado', name='estado_periodo_contable', native_enum=False), nullable=False),
    sa.Column('cerrado_por', sa.Uuid(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cerrado_por'], ['usuario.id'], name=op.f('fk_periodo_contable_cerrado_por_usuario')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_periodo_contable_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_periodo_contable')),
    sa.UniqueConstraint('empresa_id', 'anio', 'mes', name=op.f('uq_periodo_contable_empresa_id'))
    )
    op.create_table('asiento',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('periodo_contable_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('glosa', sa.String(length=255), nullable=False),
    sa.Column('origen', sa.Enum('manual', 'automatico', name='origen_asiento', native_enum=False), nullable=False),
    sa.Column('evento_origen', sa.String(length=100), nullable=True),
    sa.Column('referencia_origen', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Enum('registrado', 'anulado', name='estado_asiento', native_enum=False), nullable=False),
    sa.Column('creado_por', sa.Uuid(), nullable=True),
    sa.Column('asiento_reversa_de_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asiento_reversa_de_id'], ['asiento.id'], name=op.f('fk_asiento_asiento_reversa_de_id_asiento')),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name=op.f('fk_asiento_creado_por_usuario')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_asiento_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['periodo_contable_id'], ['periodo_contable.id'], name=op.f('fk_asiento_periodo_contable_id_periodo_contable')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asiento'))
    )
    op.create_table('regla_asiento',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('evento', sa.String(length=100), nullable=False),
    sa.Column('cuenta_debe_id', sa.Uuid(), nullable=False),
    sa.Column('cuenta_haber_id', sa.Uuid(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_debe_id'], ['cuenta_contable.id'], name=op.f('fk_regla_asiento_cuenta_debe_id_cuenta_contable')),
    sa.ForeignKeyConstraint(['cuenta_haber_id'], ['cuenta_contable.id'], name=op.f('fk_regla_asiento_cuenta_haber_id_cuenta_contable')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_regla_asiento_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regla_asiento')),
    sa.UniqueConstraint('empresa_id', 'evento', name=op.f('uq_regla_asiento_empresa_id'))
    )
    op.create_table('asiento_linea',
    sa.Column('asiento_id', sa.Uuid(), nullable=False),
    sa.Column('cuenta_contable_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('debe', 'haber', name='tipo_linea_asiento', native_enum=False), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asiento_id'], ['asiento.id'], name=op.f('fk_asiento_linea_asiento_id_asiento')),
    sa.ForeignKeyConstraint(['cuenta_contable_id'], ['cuenta_contable.id'], name=op.f('fk_asiento_linea_cuenta_contable_id_cuenta_contable')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asiento_linea'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asiento_linea')
    op.drop_table('regla_asiento')
    op.drop_table('asiento')
    op.drop_table('periodo_contable')
    op.drop_table('cuenta_contable')
    # ### end Alembic commands ###
