"""venta.referencia_atencion para KDS y comanda

Revision ID: 617845c27651
Revises: 7672566bf189
Create Date: 2026-07-25 11:41:27.283690

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401

from alembic import op  # noqa: F401

revision: str = '617845c27651'
down_revision: str | None = '7672566bf189'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venta', sa.Column('referencia_atencion', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venta', 'referencia_atencion')
    # ### end Alembic commands ###
