"""modulo delivery reparto propio

Revision ID: 69f4ca1d58f4
Revises: c4f3e14f5bce
Create Date: 2026-09-09 02:24:34.985297

Cuatro tablas del módulo `delivery` (ADR-098, `data-model.md` §6b): el
reparto propio se separa de `sales` tal como preveía `workflows.md` cuando
llegara a tener ruteo y flota propia.

`repartidor` es un trabajador con cuenta y vehículo (`trabajador_id` y
`usuario_id` únicos: un trabajador es como máximo un repartidor, y su
cuenta no puede ser la de otro). `ruta_reparto` es una salida con una o
más paradas, con la última posición conocida denormalizada
(`ultima_lat`/`ultima_lng`/...) para que el tablero y el enlace público no
tengan que leer el breadcrumb completo. `entrega` reemplaza a la fila
homónima que `data-model.md` §6 dejaba "pendiente de slice": una por venta
(`uq_entrega_venta`), con su historial de intentos y motivo de fallo.
`posicion_repartidor` es el breadcrumb GPS sin agregación, purgado por
Celery beat a los 30 días.

`venta_id` es FK a `venta.id` por nombre de tabla, no por import de
`sales` — mismo patrón que `marketing.encuesta_satisfaccion.venta_id`: es
integridad referencial de base de datos, nunca un acoplamiento de código
entre módulos (`tests/test_arquitectura.py` lo exige).

Los `Enum(..., native_enum=False)` traen su propio `CheckConstraint`
explícito (ADR-097): la columna es un `VARCHAR` con guarda en la base, no
solo en Python.
"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = '69f4ca1d58f4'
down_revision: str | None = 'c4f3e14f5bce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repartidor',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=False),
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('vehiculo_tipo', sa.Enum('moto', 'bicicleta', 'auto', 'a_pie', name='vehiculo_tipo_repartidor', native_enum=False), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("vehiculo_tipo IN ('moto', 'bicicleta', 'auto', 'a_pie')", name=op.f('ck_repartidor_vehiculo_tipo_repartidor')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_repartidor_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_repartidor_sucursal_id_sucursal')),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], name=op.f('fk_repartidor_trabajador_id_trabajador')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_repartidor_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repartidor')),
    sa.UniqueConstraint('trabajador_id', name=op.f('uq_repartidor_trabajador_id')),
    sa.UniqueConstraint('usuario_id', name=op.f('uq_repartidor_usuario_id'))
    )
    op.create_index('ix_repartidor_sucursal_activo', 'repartidor', ['sucursal_id', 'activo'], unique=False)
    op.create_table('ruta_reparto',
    sa.Column('sucursal_id', sa.Uuid(), nullable=False),
    sa.Column('repartidor_id', sa.Uuid(), nullable=False),
    sa.Column('creada_por', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('planificada', 'en_curso', 'finalizada', 'cancelada', name='estado_ruta_reparto', native_enum=False), nullable=False),
    sa.Column('hora_salida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hora_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origen_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('origen_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('distancia_m', sa.Integer(), nullable=True),
    sa.Column('duracion_seg', sa.Integer(), nullable=True),
    sa.Column('polyline', sa.Text(), nullable=True),
    sa.Column('optimizada_por', sa.Enum('google', 'heuristica', 'manual', name='optimizada_por_ruta_reparto', native_enum=False), nullable=False),
    sa.Column('ultima_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('ultima_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('ultima_precision_m', sa.Integer(), nullable=True),
    sa.Column('ultima_posicion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('planificada', 'en_curso', 'finalizada', 'cancelada')", name=op.f('ck_ruta_reparto_estado_ruta_reparto')),
    sa.CheckConstraint("optimizada_por IN ('google', 'heuristica', 'manual')", name=op.f('ck_ruta_reparto_optimizada_por_ruta_reparto')),
    sa.ForeignKeyConstraint(['creada_por'], ['usuario.id'], name=op.f('fk_ruta_reparto_creada_por_usuario')),
    sa.ForeignKeyConstraint(['repartidor_id'], ['repartidor.id'], name=op.f('fk_ruta_reparto_repartidor_id_repartidor')),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_ruta_reparto_sucursal_id_sucursal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ruta_reparto'))
    )
    op.create_index('ix_ruta_reparto_repartidor_estado', 'ruta_reparto', ['repartidor_id', 'estado'], unique=False)
    op.create_index('ix_ruta_reparto_sucursal_estado', 'ruta_reparto', ['sucursal_id', 'estado'], unique=False)
    op.create_table('entrega',
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=False),
    sa.Column('ruta_id', sa.Uuid(), nullable=True),
    sa.Column('repartidor_id', sa.Uuid(), nullable=True),
    sa.Column('orden_parada', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'asignada', 'en_ruta', 'entregada', 'fallida', 'cancelada', name='estado_entrega', native_enum=False), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('eta_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tramo_distancia_m', sa.Integer(), nullable=True),
    sa.Column('tramo_duracion_seg', sa.Integer(), nullable=True),
    sa.Column('destino_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('destino_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entregado_por', sa.Uuid(), nullable=True),
    sa.Column('motivo_fallo', sa.Enum('cliente_ausente', 'direccion_errada', 'rechazo', 'no_contesta', 'otro', name='motivo_fallo_entrega', native_enum=False), nullable=True),
    sa.Column('motivo_detalle', sa.String(length=255), nullable=True),
    sa.Column('resultado_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('resultado_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('evidencia_foto', sa.LargeBinary(), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('token_publico', sa.String(length=64), nullable=True),
    sa.Column('token_expira_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aviso_en_camino_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aviso_resultado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aviso_error', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente', 'asignada', 'en_ruta', 'entregada', 'fallida', 'cancelada')", name=op.f('ck_entrega_estado_entrega')),
    sa.CheckConstraint("motivo_fallo IS NULL OR motivo_fallo IN ('cliente_ausente', 'direccion_errada', 'rechazo', 'no_contesta', 'otro')", name=op.f('ck_entrega_motivo_fallo_entrega')),
    sa.ForeignKeyConstraint(['entregado_por'], ['usuario.id'], name=op.f('fk_entrega_entregado_por_usuario')),
    sa.ForeignKeyConstraint(['repartidor_id'], ['repartidor.id'], name=op.f('fk_entrega_repartidor_id_repartidor')),
    sa.ForeignKeyConstraint(['ruta_id'], ['ruta_reparto.id'], name=op.f('fk_entrega_ruta_id_ruta_reparto')),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_entrega_sucursal_id_sucursal')),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name=op.f('fk_entrega_venta_id_venta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entrega')),
    sa.UniqueConstraint('token_publico', name=op.f('uq_entrega_token_publico')),
    sa.UniqueConstraint('venta_id', name='uq_entrega_venta')
    )
    op.create_index('ix_entrega_ruta_orden', 'entrega', ['ruta_id', 'orden_parada'], unique=False)
    op.create_index('ix_entrega_sucursal_estado', 'entrega', ['sucursal_id', 'estado'], unique=False)
    op.create_table('posicion_repartidor',
    sa.Column('ruta_id', sa.Uuid(), nullable=False),
    sa.Column('repartidor_id', sa.Uuid(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('precision_m', sa.Integer(), nullable=True),
    sa.Column('registrado_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repartidor_id'], ['repartidor.id'], name=op.f('fk_posicion_repartidor_repartidor_id_repartidor')),
    sa.ForeignKeyConstraint(['ruta_id'], ['ruta_reparto.id'], name=op.f('fk_posicion_repartidor_ruta_id_ruta_reparto')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posicion_repartidor'))
    )
    op.create_index('ix_posicion_repartidor_ruta_registrado', 'posicion_repartidor', ['ruta_id', 'registrado_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posicion_repartidor_ruta_registrado', table_name='posicion_repartidor')
    op.drop_table('posicion_repartidor')
    op.drop_index('ix_entrega_sucursal_estado', table_name='entrega')
    op.drop_index('ix_entrega_ruta_orden', table_name='entrega')
    op.drop_table('entrega')
    op.drop_index('ix_ruta_reparto_sucursal_estado', table_name='ruta_reparto')
    op.drop_index('ix_ruta_reparto_repartidor_estado', table_name='ruta_reparto')
    op.drop_table('ruta_reparto')
    op.drop_index('ix_repartidor_sucursal_activo', table_name='repartidor')
    op.drop_table('repartidor')
    # ### end Alembic commands ###
