"""slice KDS: pantallas, estado_preparacion, categoria comercial, contador comanda

Revision ID: 7672566bf189
Revises: be914c92a94b
Create Date: 2026-07-25 11:18:09.241653

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op  # noqa: F401

revision: str = '7672566bf189'
down_revision: str | None = 'be914c92a94b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kds_pantalla',
    sa.Column('sucursal_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('preparacion', 'despacho', name='tipo_kds_pantalla', native_enum=False), nullable=False),
    sa.Column('categoria_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_kds_pantalla_sucursal_id_sucursal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kds_pantalla')),
    sa.UniqueConstraint('sucursal_id', 'nombre', name=op.f('uq_kds_pantalla_sucursal_id'))
    )
    op.add_column('producto_comercial', sa.Column('categoria_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_producto_comercial_categoria_id_categoria'), 'producto_comercial', 'categoria', ['categoria_id'], ['id'])
    # server_default: seguro aunque venta/venta_item ya tengan filas.
    op.add_column('venta', sa.Column('comanda_impresa_veces', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('venta_item', sa.Column('estado_preparacion', sa.Enum('pendiente', 'en_preparacion', 'listo', 'entregado', name='estado_preparacion_item', native_enum=False), nullable=False, server_default='pendiente'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venta_item', 'estado_preparacion')
    op.drop_column('venta', 'comanda_impresa_veces')
    op.drop_constraint(op.f('fk_producto_comercial_categoria_id_categoria'), 'producto_comercial', type_='foreignkey')
    op.drop_column('producto_comercial', 'categoria_id')
    op.drop_table('kds_pantalla')
    # ### end Alembic commands ###
