"""slice cobro y comprobante: pago, medio_pago, comprobante, caja

Revision ID: 8cde35e4f3f2
Revises: 90116965bfa8
Create Date: 2026-07-20 19:22:47.220561

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op  # noqa: F401

revision: str = '8cde35e4f3f2'
down_revision: str | None = '90116965bfa8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medio_pago',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.Enum('cobro', 'pago', 'ambos', name='direccion_medio_pago', native_enum=False), nullable=False),
    sa.Column('tipo', sa.Enum('efectivo', 'tarjeta_credito', 'tarjeta_debito', 'billetera_digital', 'transferencia', 'cheque', 'credito_empresarial', name='tipo_medio_pago', native_enum=False), nullable=False),
    sa.Column('comision_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('activa_promocion', sa.Boolean(), nullable=False),
    sa.Column('lista_precio_credito_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_medio_pago_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medio_pago'))
    )
    op.create_table('apertura_caja',
    sa.Column('punto_venta_id', sa.Uuid(), nullable=False),
    sa.Column('cajero_id', sa.Uuid(), nullable=False),
    sa.Column('relevo_encargado_id', sa.Uuid(), nullable=False),
    sa.Column('monto_apertura', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('detalle_denominaciones', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('diferencia_reportada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pos_verificados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cajero_id'], ['usuario.id'], name=op.f('fk_apertura_caja_cajero_id_usuario')),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['punto_venta.id'], name=op.f('fk_apertura_caja_punto_venta_id_punto_venta')),
    sa.ForeignKeyConstraint(['relevo_encargado_id'], ['usuario.id'], name=op.f('fk_apertura_caja_relevo_encargado_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apertura_caja'))
    )
    op.create_table('arqueo',
    sa.Column('punto_venta_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('sorpresa', 'programado', name='tipo_arqueo', native_enum=False), nullable=False),
    sa.Column('realizado_por', sa.Uuid(), nullable=False),
    sa.Column('monto_esperado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_contado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('diferencia', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('acta_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['punto_venta.id'], name=op.f('fk_arqueo_punto_venta_id_punto_venta')),
    sa.ForeignKeyConstraint(['realizado_por'], ['usuario.id'], name=op.f('fk_arqueo_realizado_por_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_arqueo'))
    )
    op.create_table('cierre_caja',
    sa.Column('apertura_caja_id', sa.Uuid(), nullable=False),
    sa.Column('cajero_id', sa.Uuid(), nullable=False),
    sa.Column('montos_esperados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('montos_reales', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('descuadre_monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuadre_atribucion', sa.Enum('cajero', 'tercero_reportado', 'encargado', name='descuadre_atribucion', native_enum=False), nullable=True),
    sa.Column('reportes_pos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('relevos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('custodia', sa.Enum('local_caja_fuerte', 'traslado_contabilidad', name='custodia_cierre_caja', native_enum=False), nullable=False),
    sa.Column('estado', sa.Enum('en_proceso', 'conforme', 'con_irregularidad', name='estado_cierre_caja', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apertura_caja_id'], ['apertura_caja.id'], name=op.f('fk_cierre_caja_apertura_caja_id_apertura_caja')),
    sa.ForeignKeyConstraint(['cajero_id'], ['usuario.id'], name=op.f('fk_cierre_caja_cajero_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cierre_caja')),
    sa.UniqueConstraint('apertura_caja_id', name=op.f('uq_cierre_caja_apertura_caja_id'))
    )
    op.create_table('comprobante',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('venta_id', sa.Uuid(), nullable=True),
    sa.Column('compra_id', sa.Uuid(), nullable=True),
    sa.Column('punto_venta_id', sa.Uuid(), nullable=True),
    sa.Column('direccion', sa.Enum('emitido', 'recibido', name='direccion_comprobante', native_enum=False), nullable=False),
    sa.Column('tipo', sa.Enum('boleta', 'factura', 'nc', 'rhe', 'ticket_compra', name='tipo_comprobante', native_enum=False), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('correlativo', sa.Integer(), nullable=False),
    sa.Column('sustento', sa.Enum('efectivo', 'voucher_medio_pago', 'movimiento_bancario', 'contrato_credito', name='sustento_comprobante', native_enum=False), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('estado_nubefact', sa.String(length=30), nullable=True),
    sa.Column('respuesta_nubefact', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_comprobante_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['punto_venta.id'], name=op.f('fk_comprobante_punto_venta_id_punto_venta')),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name=op.f('fk_comprobante_venta_id_venta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comprobante')),
    sa.UniqueConstraint('empresa_id', 'serie', 'correlativo', name=op.f('uq_comprobante_empresa_id')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_comprobante_idempotency_key'))
    )
    op.create_table('custodia_efectivo',
    sa.Column('apertura_caja_id', sa.Uuid(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('responsable_actual_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('en_caja', 'en_supervisor', 'en_contabilidad', 'disponible', name='estado_custodia_efectivo', native_enum=False), nullable=False),
    sa.Column('timestamps_relevo', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apertura_caja_id'], ['apertura_caja.id'], name=op.f('fk_custodia_efectivo_apertura_caja_id_apertura_caja')),
    sa.ForeignKeyConstraint(['responsable_actual_id'], ['usuario.id'], name=op.f('fk_custodia_efectivo_responsable_actual_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custodia_efectivo'))
    )
    op.create_table('pago',
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('medio_pago_id', sa.Uuid(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pasarela', sa.String(length=50), nullable=True),
    sa.Column('referencia_externa', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'confirmado', 'rechazado', name='estado_pago', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medio_pago_id'], ['medio_pago.id'], name=op.f('fk_pago_medio_pago_id_medio_pago')),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name=op.f('fk_pago_venta_id_venta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pago')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_pago_idempotency_key'))
    )
    op.add_column('punto_venta', sa.Column('serie_boleta', sa.String(length=10), nullable=False))
    op.add_column('punto_venta', sa.Column('serie_factura', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('punto_venta', 'serie_factura')
    op.drop_column('punto_venta', 'serie_boleta')
    op.drop_table('pago')
    op.drop_table('custodia_efectivo')
    op.drop_table('comprobante')
    op.drop_table('cierre_caja')
    op.drop_table('arqueo')
    op.drop_table('apertura_caja')
    op.drop_table('medio_pago')
    # ### end Alembic commands ###
