"""cliente.usuario_id opcional y venta.numero_orden

Revision ID: 90116965bfa8
Revises: 08c7aa59dd6e
Create Date: 2026-07-20 16:35:08.020663

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401

from alembic import op  # noqa: F401

revision: str = '90116965bfa8'
down_revision: str | None = '08c7aa59dd6e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('usuario_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_cliente_usuario_id'), 'cliente', ['usuario_id'])
    op.create_foreign_key(op.f('fk_cliente_usuario_id_usuario'), 'cliente', 'usuario', ['usuario_id'], ['id'])
    op.add_column('venta', sa.Column('fecha_orden', sa.Date(), nullable=False))
    op.add_column('venta', sa.Column('numero_orden', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_venta_sucursal_id'), 'venta', ['sucursal_id', 'fecha_orden', 'numero_orden'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_venta_sucursal_id'), 'venta', type_='unique')
    op.drop_column('venta', 'numero_orden')
    op.drop_column('venta', 'fecha_orden')
    op.drop_constraint(op.f('fk_cliente_usuario_id_usuario'), 'cliente', type_='foreignkey')
    op.drop_constraint(op.f('uq_cliente_usuario_id'), 'cliente', type_='unique')
    op.drop_column('cliente', 'usuario_id')
    # ### end Alembic commands ###
