"""slice rrhh: ciclo laboral completo (postulante, socio, contrato_laboral,
boleta_pago, memorandum, amonestacion, acta, certificado_trabajo,
liquidacion_bss, solicitud_permiso, pacto_permanencia, asistencia)

Revision ID: 9e1b6a4c7d23
Revises: cbf904a9fc1b
Create Date: 2026-07-25 15:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = '9e1b6a4c7d23'
down_revision: str | None = 'cbf904a9fc1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postulante',
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('puesto_postulado', sa.String(length=150), nullable=False),
    sa.Column('fecha_postulacion', sa.Date(), nullable=False),
    sa.Column('consentimiento_datos', sa.Boolean(), nullable=False),
    sa.Column('consentimiento_fecha', sa.Date(), nullable=True),
    sa.Column('plazo_conservacion_declarado', sa.Date(), nullable=True),
    sa.Column('cv_archivo_id', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.Enum('en_proceso', 'rechazado', 'contratado', name='estado_postulante', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cv_archivo_id'], ['archivo.id'], name=op.f('fk_postulante_cv_archivo_id_archivo')),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], name=op.f('fk_postulante_persona_id_persona')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postulante'))
    )
    op.create_table('socio',
    sa.Column('grupo_id', sa.Uuid(), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=True),
    sa.Column('persona_id', sa.Uuid(), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('ruc', sa.String(length=11), nullable=True),
    sa.Column('porcentaje_participacion', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_socio_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], name=op.f('fk_socio_grupo_id_grupo')),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], name=op.f('fk_socio_persona_id_persona')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_socio'))
    )
    op.create_table('contrato_laboral',
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('modalidad', sa.Enum('indeterminado', 'modal_inicio_incremento', 'modal_necesidad_mercado', 'modal_temporada', 'tiempo_parcial', 'jornada_reducida', name='modalidad_contrato_laboral', native_enum=False), nullable=False),
    sa.Column('jornada_horas_semana', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('remuneracion', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('borrador', 'firmado', 'finalizado', name='estado_contrato_laboral', native_enum=False), nullable=False),
    sa.Column('fecha_firma', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], name=op.f('fk_contrato_laboral_trabajador_id_trabajador')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contrato_laboral'))
    )
    op.create_table('boleta_pago',
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('dias_laborados', sa.Integer(), nullable=False),
    sa.Column('remuneracion', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ingresos', sa.JSON(), nullable=False),
    sa.Column('descuentos', sa.JSON(), nullable=False),
    sa.Column('aportes_empleador', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('neto_pagar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('constancia_firmada', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], name=op.f('fk_boleta_pago_trabajador_id_trabajador')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boleta_pago')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_boleta_pago_idempotency_key'))
    )
    op.create_table('memorandum',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('emisor_id', sa.Uuid(), nullable=False),
    sa.Column('destinatario_trabajador_id', sa.Uuid(), nullable=True),
    sa.Column('destinatario_area', sa.String(length=100), nullable=True),
    sa.Column('asunto', sa.String(length=200), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destinatario_trabajador_id'], ['trabajador.id'], name=op.f('fk_memorandum_destinatario_trabajador_id_trabajador')),
    sa.ForeignKeyConstraint(['emisor_id'], ['usuario.id'], name=op.f('fk_memorandum_emisor_id_usuario')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_memorandum_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memorandum'))
    )
    op.create_table('amonestacion',
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('verbal', 'escrita', name='tipo_amonestacion', native_enum=False), nullable=False),
    sa.Column('falta', sa.Text(), nullable=False),
    sa.Column('fecha_hecho', sa.Date(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('emisor_id', sa.Uuid(), nullable=False),
    sa.Column('descargo', sa.Text(), nullable=True),
    sa.Column('descargo_plazo_dias', sa.Integer(), nullable=True),
    sa.Column('sancion_relacionada', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emisor_id'], ['usuario.id'], name=op.f('fk_amonestacion_emisor_id_usuario')),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], name=op.f('fk_amonestacion_trabajador_id_trabajador')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amonestacion'))
    )
    op.create_table('acta',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('reunion', 'incidente', 'entrega_cargo', 'arqueo', 'verificacion', name='tipo_acta', native_enum=False), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('lugar', sa.String(length=200), nullable=False),
    sa.Column('hechos', sa.Text(), nullable=False),
    sa.Column('participantes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_acta_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acta'))
    )
    op.create_table('certificado_trabajo',
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('tiempo_servicios_meses', sa.Integer(), nullable=False),
    sa.Column('cargos', sa.String(length=255), nullable=False),
    sa.Column('conducta_desempeno', sa.Text(), nullable=True),
    sa.Column('dentro_de_plazo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], name=op.f('fk_certificado_trabajo_trabajador_id_trabajador')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificado_trabajo'))
    )
    op.create_table('liquidacion_bss',
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_cese', sa.Date(), nullable=False),
    sa.Column('cts_pendiente', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vacaciones_truncas', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gratificacion_trunca', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('otros_adeudos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('dentro_de_plazo', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], name=op.f('fk_liquidacion_bss_trabajador_id_trabajador')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_liquidacion_bss')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_liquidacion_bss_idempotency_key'))
    )
    op.create_table('solicitud_permiso',
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('vacaciones', 'licencia_con_goce', 'licencia_sin_goce', 'permiso_horas', name='tipo_solicitud_permiso', native_enum=False), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('horas', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'rechazada', name='estado_solicitud_permiso', native_enum=False), nullable=False),
    sa.Column('aprobador_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprobador_id'], ['usuario.id'], name=op.f('fk_solicitud_permiso_aprobador_id_usuario')),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], name=op.f('fk_solicitud_permiso_trabajador_id_trabajador')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solicitud_permiso'))
    )
    op.create_table('pacto_permanencia',
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('capacitacion_descripcion', sa.String(length=255), nullable=False),
    sa.Column('capacitacion_tipo', sa.Enum('curso', 'posgrado', 'diplomado', 'capacitacion', name='tipo_capacitacion_pacto', native_enum=False), nullable=False),
    sa.Column('costo_financiado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('plazo_permanencia_meses', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin_compromiso', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], name=op.f('fk_pacto_permanencia_trabajador_id_trabajador')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pacto_permanencia'))
    )
    op.create_table('asistencia',
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=True),
    sa.Column('hora_salida', sa.Time(), nullable=True),
    sa.Column('tardanza_min', sa.Integer(), nullable=False),
    sa.Column('horas_extra', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], name=op.f('fk_asistencia_trabajador_id_trabajador')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asistencia')),
    sa.UniqueConstraint('trabajador_id', 'fecha', name=op.f('uq_asistencia_trabajador_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asistencia')
    op.drop_table('pacto_permanencia')
    op.drop_table('solicitud_permiso')
    op.drop_table('liquidacion_bss')
    op.drop_table('certificado_trabajo')
    op.drop_table('acta')
    op.drop_table('amonestacion')
    op.drop_table('memorandum')
    op.drop_table('boleta_pago')
    op.drop_table('contrato_laboral')
    op.drop_table('socio')
    op.drop_table('postulante')
    # ### end Alembic commands ###
