"""bloque transversal y organizacion

Revision ID: a06c1d0a0913
Revises: 
Create Date: 2026-07-20 12:40:01.268982

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op  # noqa: F401

revision: str = 'a06c1d0a0913'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivo',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('tamano_bytes', sa.BigInteger(), nullable=False),
    sa.Column('url_storage', sa.String(length=500), nullable=False),
    sa.Column('origen', sa.Enum('generado', 'subido', name='origen_archivo', native_enum=False), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Uuid(), nullable=False),
    sa.Column('plantilla_id', sa.Uuid(), nullable=True),
    sa.Column('subido_por', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archivo'))
    )
    op.create_index(op.f('ix_archivo_entidad_id'), 'archivo', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_archivo_entidad_tipo'), 'archivo', ['entidad_tipo'], unique=False)
    op.create_table('categoria_udm',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('unidad_base_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categoria_udm')),
    sa.UniqueConstraint('nombre', name=op.f('uq_categoria_udm_nombre'))
    )
    op.create_table('grupo',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grupo')),
    sa.UniqueConstraint('nombre', name=op.f('uq_grupo_nombre'))
    )
    op.create_table('persona',
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('tipo_documento', sa.Enum('dni', 'ce', 'pasaporte', name='tipo_documento', native_enum=False), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('domicilio', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persona')),
    sa.UniqueConstraint('numero_documento', name=op.f('uq_persona_numero_documento'))
    )
    op.create_table('empresa',
    sa.Column('grupo_id', sa.Uuid(), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('domicilio_fiscal', sa.String(length=255), nullable=False),
    sa.Column('contacto', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.Enum('operativa', 'logistica', 'servicios', 'asesoria', 'transporte', name='tipo_empresa', native_enum=False), nullable=False),
    sa.Column('zona_tributaria', sa.Enum('amazonia_ley27037', 'general', name='zona_tributaria', native_enum=False), nullable=False),
    sa.Column('config_fiscal', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], name=op.f('fk_empresa_grupo_id_grupo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresa')),
    sa.UniqueConstraint('ruc', name=op.f('uq_empresa_ruc'))
    )
    op.create_table('marca',
    sa.Column('grupo_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('skins', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], name=op.f('fk_marca_grupo_id_grupo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marca')),
    sa.UniqueConstraint('grupo_id', 'nombre', name=op.f('uq_marca_grupo_id'))
    )
    op.create_table('unidad_medida',
    sa.Column('categoria_udm_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_udm_id'], ['categoria_udm.id'], name=op.f('fk_unidad_medida_categoria_udm_id_categoria_udm')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unidad_medida')),
    sa.UniqueConstraint('categoria_udm_id', 'nombre', name=op.f('uq_unidad_medida_categoria_udm_id'))
    )
    op.create_table('categoria',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('asiento_contable_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_categoria_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categoria')),
    sa.UniqueConstraint('empresa_id', 'nombre', name=op.f('uq_categoria_empresa_id'))
    )
    op.create_table('licencia_marca',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('marca_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_licencia_marca_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], name=op.f('fk_licencia_marca_marca_id_marca')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licencia_marca')),
    sa.UniqueConstraint('empresa_id', 'marca_id', name=op.f('uq_licencia_marca_empresa_id'))
    )
    op.create_table('sucursal',
    sa.Column('marca_id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'inactiva', name='estado_sucursal', native_enum=False), nullable=False),
    sa.Column('tenencia', sa.Enum('propia', 'alquilada', 'del_grupo', name='tenencia_sucursal', native_enum=False), nullable=False),
    sa.Column('horario_atencion', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_sucursal_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], name=op.f('fk_sucursal_marca_id_marca')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sucursal'))
    )
    op.create_table('almacen',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('almacen_abastecedor_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['almacen_abastecedor_id'], ['almacen.id'], name=op.f('fk_almacen_almacen_abastecedor_id_almacen')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_almacen_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_almacen_sucursal_id_sucursal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_almacen'))
    )
    # FK circular categoria_udm→unidad_medida: Alembic no emite FKs con
    # use_alter dentro de create_table, así que se crea explícita al final.
    op.create_foreign_key(
        op.f('fk_categoria_udm_unidad_base_id_unidad_medida'),
        'categoria_udm',
        'unidad_medida',
        ['unidad_base_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # FK circular categoria_udm→unidad_medida: soltarla antes de borrar tablas.
    op.drop_constraint(
        op.f('fk_categoria_udm_unidad_base_id_unidad_medida'),
        'categoria_udm',
        type_='foreignkey',
    )
    op.drop_table('almacen')
    op.drop_table('sucursal')
    op.drop_table('licencia_marca')
    op.drop_table('categoria')
    op.drop_table('unidad_medida')
    op.drop_table('marca')
    op.drop_table('empresa')
    op.drop_table('persona')
    op.drop_table('grupo')
    op.drop_table('categoria_udm')
    op.drop_index(op.f('ix_archivo_entidad_tipo'), table_name='archivo')
    op.drop_index(op.f('ix_archivo_entidad_id'), table_name='archivo')
    op.drop_table('archivo')
    # ### end Alembic commands ###
