"""persona_version_lock_y_regla_aprobacion

Revision ID: af8a246e2c25
Revises: f78501175fba
Create Date: 2026-07-25 14:31:30.509741

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = 'af8a246e2c25'
down_revision: str | None = 'f78501175fba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regla_aprobacion',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('umbral', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('permiso_requerido', sa.String(length=100), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_regla_aprobacion_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regla_aprobacion')),
    sa.UniqueConstraint('empresa_id', 'modulo', 'codigo', name=op.f('uq_regla_aprobacion_empresa_id'))
    )
    # server_default solo para el backfill de filas existentes; el default
    # real de nuevas filas lo pone el ORM (VersionedMixin, default=1).
    op.add_column(
        'persona',
        sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'version')
    op.drop_table('regla_aprobacion')
    # ### end Alembic commands ###
