"""slice inventory core: stock, movimiento_inventario, ajuste

Revision ID: be914c92a94b
Revises: c16d615f6afd
Create Date: 2026-07-25 10:11:56.046577

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401

from alembic import op  # noqa: F401

revision: str = 'be914c92a94b'
down_revision: str | None = 'c16d615f6afd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimiento_inventario',
    sa.Column('almacen_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('tipo', sa.Enum('recepcion_compra', 'transferencia_salida', 'transferencia_entrada', 'consumo_venta', 'consumo_produccion', 'produccion_entrada', 'ajuste', 'devolucion', name='tipo_movimiento', native_enum=False), nullable=False),
    sa.Column('motivo_ajuste', sa.Enum('sobrante', 'faltante', 'merma', 'error_registro', name='motivo_ajuste', native_enum=False), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacen.id'], name=op.f('fk_movimiento_inventario_almacen_id_almacen')),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name=op.f('fk_movimiento_inventario_sku_id_sku')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_movimiento_inventario_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimiento_inventario'))
    )
    op.create_table('stock',
    sa.Column('almacen_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('stock_maximo', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacen.id'], name=op.f('fk_stock_almacen_id_almacen')),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name=op.f('fk_stock_sku_id_sku')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock')),
    sa.UniqueConstraint('almacen_id', 'sku_id', name=op.f('uq_stock_almacen_id'))
    )
    op.create_table('ajuste',
    sa.Column('almacen_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('motivo', sa.Enum('sobrante', 'faltante', 'merma', 'error_registro', name='motivo_ajuste', native_enum=False), nullable=False),
    sa.Column('solicitado_por', sa.Uuid(), nullable=False),
    sa.Column('aprobado_por', sa.Uuid(), nullable=True),
    sa.Column('dentro_margen', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado', name='estado_ajuste', native_enum=False), nullable=False),
    sa.Column('movimiento_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacen.id'], name=op.f('fk_ajuste_almacen_id_almacen')),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuario.id'], name=op.f('fk_ajuste_aprobado_por_usuario')),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimiento_inventario.id'], name=op.f('fk_ajuste_movimiento_id_movimiento_inventario')),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name=op.f('fk_ajuste_sku_id_sku')),
    sa.ForeignKeyConstraint(['solicitado_por'], ['usuario.id'], name=op.f('fk_ajuste_solicitado_por_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ajuste'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ajuste')
    op.drop_table('stock')
    op.drop_table('movimiento_inventario')
    # ### end Alembic commands ###
