"""slice auth: RBAC, refresh_token, audit_log, lockout usuario

Revision ID: c16d615f6afd
Revises: 8cde35e4f3f2
Create Date: 2026-07-25 09:32:53.386740

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op  # noqa: F401

revision: str = 'c16d615f6afd'
down_revision: str | None = '8cde35e4f3f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permiso',
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('restricciones', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permiso')),
    sa.UniqueConstraint('codigo', name=op.f('uq_permiso_codigo'))
    )
    op.create_table('rol',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rol')),
    sa.UniqueConstraint('nombre', name=op.f('uq_rol_nombre'))
    )
    op.create_table('rol_permiso',
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('permiso_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], name=op.f('fk_rol_permiso_permiso_id_permiso')),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], name=op.f('fk_rol_permiso_rol_id_rol')),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id', name=op.f('pk_rol_permiso'))
    )
    op.create_table('refresh_token',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('sesion_id', sa.Uuid(), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_refresh_token_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_token_token_hash'))
    )
    op.create_table('usuario_rol',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], name=op.f('fk_usuario_rol_rol_id_rol')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_usuario_rol_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id', name=op.f('pk_usuario_rol'))
    )
    op.create_table('audit_log',
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.Uuid(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('datos_antes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('datos_despues', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('sucursal_id', sa.Uuid(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_audit_log_sucursal_id_sucursal')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_audit_log_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('usuario_sucursal',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], name=op.f('fk_usuario_sucursal_sucursal_id_sucursal')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_usuario_sucursal_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('usuario_id', 'sucursal_id', name=op.f('pk_usuario_sucursal'))
    )
    op.add_column('usuario', sa.Column('intentos_fallidos', sa.Integer(), nullable=False))
    op.add_column('usuario', sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'bloqueado_hasta')
    op.drop_column('usuario', 'intentos_fallidos')
    op.drop_table('usuario_sucursal')
    op.drop_table('audit_log')
    op.drop_table('usuario_rol')
    op.drop_table('refresh_token')
    op.drop_table('rol_permiso')
    op.drop_table('rol')
    op.drop_table('permiso')
    # ### end Alembic commands ###
