"""conteo ciclico: conteo, conteo_item y frecuencia por categoria

Cierra el conteo cíclico de `inventory` (ADR-017, RN-INV-007/014/021).

`categoria.frecuencia_conteo` es la pieza que define el calendario: la
periodicidad no es universal ni por empresa, la fija cada categoría — el
perecible se cuenta a diario y el abarrote al mes. NULL deja la categoría
fuera del ciclo, que es el estado en que quedan todas las existentes: la
migración no rellena nada, Gerencia configura cada categoría cuando
corresponda.

No hay tabla de calendario: la próxima fecha se deriva del último conteo
cerrado más la frecuencia. Una tabla de programación habría que mantenerla
en sincronía con cada conteo, cada alta de categoría y cada alta de
almacén; lo derivado no se desincroniza.

`ajuste.conteo_id` liga la corrección con el conteo que la descubrió —
sin eso, un ajuste nacido de un recuento es indistinguible de uno pedido
a mano y la auditoría pierde el hilo.

Revision ID: c4e70a91d5b8
Revises: b6d41e07af92
Create Date: 2026-08-01 15:18:53.925736

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = 'c4e70a91d5b8'
down_revision: str | None = 'b6d41e07af92'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conteo',
    sa.Column('almacen_id', sa.Uuid(), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.Enum('rutina', 'ajuste', 'auditoria', name='tipo_conteo', native_enum=False), nullable=False),
    sa.Column('estado', sa.Enum('abierto', 'cerrado', 'anulado', name='estado_conteo', native_enum=False), nullable=False),
    sa.Column('fecha_programada', sa.Date(), nullable=True),
    sa.Column('abierto_por', sa.Uuid(), nullable=False),
    sa.Column('cerrado_por', sa.Uuid(), nullable=True),
    sa.Column('cerrado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacion', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['abierto_por'], ['usuario.id'], name=op.f('fk_conteo_abierto_por_usuario')),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacen.id'], name=op.f('fk_conteo_almacen_id_almacen')),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('fk_conteo_categoria_id_categoria')),
    sa.ForeignKeyConstraint(['cerrado_por'], ['usuario.id'], name=op.f('fk_conteo_cerrado_por_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conteo'))
    )
    op.create_table('conteo_item',
    sa.Column('conteo_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad_sistema', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cantidad_contada', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conteo_id'], ['conteo.id'], name=op.f('fk_conteo_item_conteo_id_conteo')),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name=op.f('fk_conteo_item_sku_id_sku')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conteo_item')),
    sa.UniqueConstraint('conteo_id', 'sku_id', name=op.f('uq_conteo_item_conteo_id'))
    )
    op.add_column('ajuste', sa.Column('conteo_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_ajuste_conteo_id_conteo'), 'ajuste', 'conteo', ['conteo_id'], ['id'])
    op.add_column('categoria', sa.Column('frecuencia_conteo', sa.Enum('diario', 'semanal', 'quincenal', 'mensual', 'semestral', 'anual', name='frecuencia_conteo', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categoria', 'frecuencia_conteo')
    op.drop_constraint(op.f('fk_ajuste_conteo_id_conteo'), 'ajuste', type_='foreignkey')
    op.drop_column('ajuste', 'conteo_id')
    op.drop_table('conteo_item')
    op.drop_table('conteo')
    # ### end Alembic commands ###
