"""activo depreciacion en accounting

Revision ID: c78b01a58f2a
Revises: 568b2a1dfcca
Create Date: 2026-09-09 16:13:21.470121

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = "c78b01a58f2a"
down_revision: str | None = "568b2a1dfcca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activo_depreciacion",
        sa.Column("empresa_id", sa.Uuid(), nullable=False),
        sa.Column("activo_id", sa.Uuid(), nullable=False),
        sa.Column("valor_compra", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("vida_util_meses", sa.Integer(), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("depreciado_acumulado", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"], ["empresa.id"], name=op.f("fk_activo_depreciacion_empresa_id_empresa")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activo_depreciacion")),
        sa.UniqueConstraint("activo_id", name="uq_activo_depreciacion_activo_id"),
    )
    op.create_index(
        op.f("ix_activo_depreciacion_empresa_id"),
        "activo_depreciacion",
        ["empresa_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activo_depreciacion_empresa_id"), table_name="activo_depreciacion")
    op.drop_table("activo_depreciacion")
    # ### end Alembic commands ###
