"""slice pago a proveedor: movimiento_dinero

Revision ID: cbf904a9fc1b
Revises: 5402d99333fa
Create Date: 2026-07-25 15:43:41.707130

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = 'cbf904a9fc1b'
down_revision: str | None = '5402d99333fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimiento_dinero',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('egreso', 'ingreso', name='tipo_movimiento_dinero', native_enum=False), nullable=False),
    sa.Column('concepto', sa.String(length=50), nullable=False),
    sa.Column('comprobante_id', sa.Uuid(), nullable=True),
    sa.Column('proveedor_id', sa.Uuid(), nullable=True),
    sa.Column('orden_compra_id', sa.Uuid(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_detraccion', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('medio_pago', sa.Enum('transferencia', 'cheque', 'efectivo', name='medio_pago_movimiento_dinero', native_enum=False), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'ejecutado', 'rechazado', name='estado_movimiento_dinero', native_enum=False), nullable=False),
    sa.Column('solicitado_por', sa.Uuid(), nullable=True),
    sa.Column('aprobado_por', sa.Uuid(), nullable=True),
    sa.Column('asiento_id', sa.Uuid(), nullable=True),
    sa.Column('fecha_ejecucion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('constancia', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuario.id'], name=op.f('fk_movimiento_dinero_aprobado_por_usuario')),
    sa.ForeignKeyConstraint(['asiento_id'], ['asiento.id'], name=op.f('fk_movimiento_dinero_asiento_id_asiento')),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobante.id'], name=op.f('fk_movimiento_dinero_comprobante_id_comprobante')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_movimiento_dinero_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['solicitado_por'], ['usuario.id'], name=op.f('fk_movimiento_dinero_solicitado_por_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimiento_dinero')),
    sa.UniqueConstraint('comprobante_id', name=op.f('uq_movimiento_dinero_comprobante_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimiento_dinero')
    # ### end Alembic commands ###
