"""reserva de stock, solicitud de insumos y transferencias

Cierra el ciclo de abastecimiento interno (ADR-018, RN-INV-001..003,
RN-INV-009..011): el local pide, el supervisor aprueba y reserva, el
central despacha, el local recibe.

`reserva_stock` es la pieza que faltaba para que el stock signifique algo
entre esos pasos: entre que se aprueba y se arma el picking pasan horas, y
sin reserva dos sucursales se prometen el mismo saco de harina. No mueve
`stock` —lo que ya salió es un movimiento, no una reserva—; el disponible
pasa a ser físico menos reservas activas.

`transferencia_item` va por SKU **y lote**: el despacho reparte por FEFO,
así que sacar 10 kg puede tomar tres lotes y el destino tiene que recibir
esos mismos tres (ADR-015). Una fila por movimiento de salida.

Tablas nuevas, sin backfill ni columnas agregadas a tablas existentes: no
hay nada que migrar, el ciclo arranca vacío.

Revision ID: d8b35f1ca207
Revises: c4e70a91d5b8
Create Date: 2026-08-01 15:49:41.158044

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = 'd8b35f1ca207'
down_revision: str | None = 'c4e70a91d5b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_insumos',
    sa.Column('almacen_solicitante_id', sa.Uuid(), nullable=False),
    sa.Column('almacen_abastecedor_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'rechazada', 'cancelada', 'despachada', 'recibida', name='estado_solicitud', native_enum=False), nullable=False),
    sa.Column('solicitado_por', sa.Uuid(), nullable=False),
    sa.Column('aprobado_por', sa.Uuid(), nullable=True),
    sa.Column('observacion', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['almacen_abastecedor_id'], ['almacen.id'], name=op.f('fk_solicitud_insumos_almacen_abastecedor_id_almacen')),
    sa.ForeignKeyConstraint(['almacen_solicitante_id'], ['almacen.id'], name=op.f('fk_solicitud_insumos_almacen_solicitante_id_almacen')),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuario.id'], name=op.f('fk_solicitud_insumos_aprobado_por_usuario')),
    sa.ForeignKeyConstraint(['solicitado_por'], ['usuario.id'], name=op.f('fk_solicitud_insumos_solicitado_por_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solicitud_insumos'))
    )
    op.create_table('reserva_stock',
    sa.Column('almacen_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('tipo', sa.Enum('solicitud', 'produccion', 'merma', 'carrito', name='tipo_reserva', native_enum=False), nullable=False),
    sa.Column('referencia_id', sa.Uuid(), nullable=True),
    sa.Column('motivo', sa.Enum('devolucion', 'rechazo_sucursal', 'auditoria', name='motivo_reserva_merma', native_enum=False), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'liberada', 'consumida', 'pendiente_desecho', name='estado_reserva', native_enum=False), nullable=False),
    sa.Column('creado_por', sa.Uuid(), nullable=False),
    sa.Column('liberado_por', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacen.id'], name=op.f('fk_reserva_stock_almacen_id_almacen')),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name=op.f('fk_reserva_stock_creado_por_usuario')),
    sa.ForeignKeyConstraint(['liberado_por'], ['usuario.id'], name=op.f('fk_reserva_stock_liberado_por_usuario')),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name=op.f('fk_reserva_stock_sku_id_sku')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reserva_stock'))
    )
    op.create_table('solicitud_item',
    sa.Column('solicitud_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad_solicitada', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cantidad_aprobada', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cantidad_despachada', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name=op.f('fk_solicitud_item_sku_id_sku')),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud_insumos.id'], name=op.f('fk_solicitud_item_solicitud_id_solicitud_insumos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solicitud_item')),
    sa.UniqueConstraint('solicitud_id', 'sku_id', name=op.f('uq_solicitud_item_solicitud_id'))
    )
    op.create_table('transferencia',
    sa.Column('origen_almacen_id', sa.Uuid(), nullable=False),
    sa.Column('destino_almacen_id', sa.Uuid(), nullable=False),
    sa.Column('solicitud_id', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.Enum('en_transito', 'recibida', name='estado_transferencia', native_enum=False), nullable=False),
    sa.Column('despachado_por', sa.Uuid(), nullable=False),
    sa.Column('recibido_por', sa.Uuid(), nullable=True),
    sa.Column('transportista_id', sa.Uuid(), nullable=True),
    sa.Column('recibida_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacion', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['despachado_por'], ['usuario.id'], name=op.f('fk_transferencia_despachado_por_usuario')),
    sa.ForeignKeyConstraint(['destino_almacen_id'], ['almacen.id'], name=op.f('fk_transferencia_destino_almacen_id_almacen')),
    sa.ForeignKeyConstraint(['origen_almacen_id'], ['almacen.id'], name=op.f('fk_transferencia_origen_almacen_id_almacen')),
    sa.ForeignKeyConstraint(['recibido_por'], ['usuario.id'], name=op.f('fk_transferencia_recibido_por_usuario')),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud_insumos.id'], name=op.f('fk_transferencia_solicitud_id_solicitud_insumos')),
    sa.ForeignKeyConstraint(['transportista_id'], ['usuario.id'], name=op.f('fk_transferencia_transportista_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transferencia'))
    )
    op.create_table('transferencia_item',
    sa.Column('transferencia_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('lote_id', sa.Uuid(), nullable=True),
    sa.Column('cantidad_enviada', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cantidad_recibida', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], name=op.f('fk_transferencia_item_lote_id_lote')),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name=op.f('fk_transferencia_item_sku_id_sku')),
    sa.ForeignKeyConstraint(['transferencia_id'], ['transferencia.id'], name=op.f('fk_transferencia_item_transferencia_id_transferencia')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transferencia_item'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transferencia_item')
    op.drop_table('transferencia')
    op.drop_table('solicitud_item')
    op.drop_table('reserva_stock')
    op.drop_table('solicitud_insumos')
    # ### end Alembic commands ###
