"""oc tipo activo y requerimiento_activo

Revision ID: e0ef2e91cadc
Revises: c78b01a58f2a
Create Date: 2026-09-09 16:27:44.632494

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = "e0ef2e91cadc"
down_revision: str | None = "c78b01a58f2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requerimiento_activo",
        sa.Column("empresa_id", sa.Uuid(), nullable=False),
        sa.Column("sucursal_id", sa.Uuid(), nullable=True),
        sa.Column("id_interno", sa.String(length=8), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("categoria", sa.String(length=60), nullable=True),
        sa.Column("marca", sa.String(length=60), nullable=True),
        sa.Column("modelo", sa.String(length=60), nullable=True),
        sa.Column("costo_estimado", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("vida_util_meses", sa.Integer(), nullable=True),
        sa.Column("solicitado_por", sa.Uuid(), nullable=False),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"], ["empresa.id"], name=op.f("fk_requerimiento_activo_empresa_id_empresa")
        ),
        sa.ForeignKeyConstraint(
            ["solicitado_por"],
            ["usuario.id"],
            name=op.f("fk_requerimiento_activo_solicitado_por_usuario"),
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"],
            ["sucursal.id"],
            name=op.f("fk_requerimiento_activo_sucursal_id_sucursal"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requerimiento_activo")),
    )
    op.create_index(
        op.f("ix_requerimiento_activo_empresa_id"),
        "requerimiento_activo",
        ["empresa_id"],
        unique=False,
    )
    op.alter_column("orden_compra", "almacen_destino_id", existing_type=sa.UUID(), nullable=True)
    op.create_foreign_key(
        op.f("fk_orden_compra_requerimiento_activo_id_requerimiento_activo"),
        "orden_compra",
        "requerimiento_activo",
        ["requerimiento_activo_id"],
        ["id"],
    )
    # Autogenerate no compara el cuerpo de un CheckConstraint existente ni
    # detecta uno nuevo: se agrega a mano.
    op.create_check_constraint(
        "requerimiento_activo_si_tipo_activo",
        "orden_compra",
        "(tipo = 'activo') = (requerimiento_activo_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("requerimiento_activo_si_tipo_activo", "orden_compra", type_="check")
    op.drop_constraint(
        op.f("fk_orden_compra_requerimiento_activo_id_requerimiento_activo"),
        "orden_compra",
        type_="foreignkey",
    )
    op.alter_column("orden_compra", "almacen_destino_id", existing_type=sa.UUID(), nullable=False)
    op.drop_index(op.f("ix_requerimiento_activo_empresa_id"), table_name="requerimiento_activo")
    op.drop_table("requerimiento_activo")
    # ### end Alembic commands ###
