"""guia remision vehiculo id desde assets

Revision ID: e5b094528cc9
Revises: ea2058d6603c
Create Date: 2026-09-09 15:44:10.556510

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = "e5b094528cc9"
down_revision: str | None = "ea2058d6603c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("guia_remision", sa.Column("vehiculo_id", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guia_remision", "vehiculo_id")
    # ### end Alembic commands ###
