"""slice assets repuestos y consumo mantenimiento

Revision ID: ea2058d6603c
Revises: 30270ac890b1
Create Date: 2026-09-09 15:28:01.179982

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = "ea2058d6603c"
down_revision: str | None = "30270ac890b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repuesto_compatibilidad",
        sa.Column("activo_id", sa.Uuid(), nullable=False),
        sa.Column("articulo_id", sa.Uuid(), nullable=False),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activo_id"], ["activo.id"], name=op.f("fk_repuesto_compatibilidad_activo_id_activo")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repuesto_compatibilidad")),
        sa.UniqueConstraint("activo_id", "articulo_id", name="uq_repuesto_compatibilidad"),
    )
    op.create_table(
        "orden_mantenimiento_repuesto",
        sa.Column("orden_mantenimiento_id", sa.Uuid(), nullable=False),
        sa.Column("articulo_id", sa.Uuid(), nullable=False),
        sa.Column("nombre_articulo", sa.String(length=120), nullable=False),
        sa.Column("cantidad", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("costo_unitario", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["orden_mantenimiento_id"],
            ["orden_mantenimiento.id"],
            name=op.f("fk_orden_mantenimiento_repuesto_orden_mantenimiento_id_orden_mantenimiento"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orden_mantenimiento_repuesto")),
    )
    # Autogenerate no compara el cuerpo de un CheckConstraint existente: los
    # nuevos valores 'consumo_mantenimiento' y 'orden_mantenimiento'
    # (repuesto de una orden de mantenimiento, RN-MNT-006) se agregan a mano.
    op.drop_constraint("tipo_movimiento", "movimiento_inventario", type_="check")
    op.create_check_constraint(
        "tipo_movimiento",
        "movimiento_inventario",
        "tipo IN ('recepcion_compra', 'transferencia_salida', "
        "'transferencia_entrada', 'consumo_venta', 'consumo_produccion', "
        "'consumo_interno', 'consumo_mantenimiento', 'produccion_entrada', "
        "'ajuste', 'devolucion', 'carga_inicial')",
    )
    op.drop_constraint("origen_incidencia_inventario", "incidencia_inventario", type_="check")
    # El VARCHAR se dimensiona al valor más largo del Enum (native_enum=False):
    # 'orden_mantenimiento' (19) supera a 'orden_produccion' (16).
    op.alter_column(
        "incidencia_inventario",
        "origen",
        existing_type=sa.String(length=16),
        type_=sa.String(length=19),
    )
    op.create_check_constraint(
        "origen_incidencia_inventario",
        "incidencia_inventario",
        "origen IN ('venta', 'orden_compra', 'orden_produccion', 'orden_mantenimiento')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("origen_incidencia_inventario", "incidencia_inventario", type_="check")
    op.alter_column(
        "incidencia_inventario",
        "origen",
        existing_type=sa.String(length=19),
        type_=sa.String(length=16),
    )
    op.create_check_constraint(
        "origen_incidencia_inventario",
        "incidencia_inventario",
        "origen IN ('venta', 'orden_compra', 'orden_produccion')",
    )
    op.drop_constraint("tipo_movimiento", "movimiento_inventario", type_="check")
    op.create_check_constraint(
        "tipo_movimiento",
        "movimiento_inventario",
        "tipo IN ('recepcion_compra', 'transferencia_salida', "
        "'transferencia_entrada', 'consumo_venta', 'consumo_produccion', "
        "'consumo_interno', 'produccion_entrada', 'ajuste', 'devolucion', "
        "'carga_inicial')",
    )
    op.drop_table("orden_mantenimiento_repuesto")
    op.drop_table("repuesto_compatibilidad")
    # ### end Alembic commands ###
