"""slice production core: orden_produccion, consumo_produccion_item, receta.articulo_id

Revision ID: f78501175fba
Revises: 4ff85f833b29
Create Date: 2026-07-25 14:26:46.174365

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

revision: str = 'f78501175fba'
down_revision: str | None = '4ff85f833b29'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orden_produccion',
    sa.Column('articulo_id', sa.Uuid(), nullable=False),
    sa.Column('almacen_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad_planeada', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cantidad_producida', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('estado', sa.Enum('borrador', 'en_proceso', 'conforme', 'no_conforme_reprocesado', 'no_conforme_desechado', name='estado_orden_produccion', native_enum=False), nullable=False),
    sa.Column('horas_hombre', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('costo_insumos', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('costo_mano_obra', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('costo_real_unitario', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('merma_cantidad', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('merma_motivo', sa.String(length=255), nullable=True),
    sa.Column('evidencia_destruccion_url', sa.String(length=500), nullable=True),
    sa.Column('creado_por', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacen.id'], name=op.f('fk_orden_produccion_almacen_id_almacen')),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], name=op.f('fk_orden_produccion_articulo_id_articulo')),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], name=op.f('fk_orden_produccion_creado_por_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orden_produccion')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_orden_produccion_idempotency_key'))
    )
    op.create_table('consumo_produccion_item',
    sa.Column('orden_produccion_id', sa.Uuid(), nullable=False),
    sa.Column('articulo_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('peso_desperdicio_real', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('tipo_desperdicio', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], name=op.f('fk_consumo_produccion_item_articulo_id_articulo')),
    sa.ForeignKeyConstraint(['orden_produccion_id'], ['orden_produccion.id'], name=op.f('fk_consumo_produccion_item_orden_produccion_id_orden_produccion')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumo_produccion_item'))
    )
    op.add_column('receta', sa.Column('articulo_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_receta_articulo_id_articulo'), 'receta', 'articulo', ['articulo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_receta_articulo_id_articulo'), 'receta', type_='foreignkey')
    op.drop_column('receta', 'articulo_id')
    op.drop_table('consumo_produccion_item')
    op.drop_table('orden_produccion')
    # ### end Alembic commands ###
